<?php

$changed_field = [
    'viewAllDashboards' => 'Просмотр дашбордов с заявками всех направлений, команд и пользователей',
    'viewDashboardsByCommand' => 'Просмотр дашбордов для супервизоров по своей команде',
    'viewDashboardsByDirection' => 'Просмотр дашбордов по заявкам направления Маркет',
    'viewOwnDashboards' => 'Просмотр дашбордов по своим заявкам',
    'blockUser' => 'Блокирование пользователей',
    'createUser' => 'Создание пользователей',
    'errorsUpdate' => 'Редактирование истории ошибок',
    'updateUser' => 'Изменение пользователей',
    'viewUser' => 'Просмотр пользователей',
    'reportLoadAllUsers' => 'Выгрузка отчетов по всем пользователям',
    'reportLoadMarketUsers' => 'Выгрузка отчетов по пользователям направления Маркетплейс',
    'reportLoadYourTeam' => 'Выгрузка отчетов по своей комманде',
    'reportView' => 'Просмотр отчетов',
    'requestAddAttrOrValues' => 'Добавление параметров/значений',
    'requestAddFatPortalCat' => 'Добавление нового портала/раздела фат-меню/категории товаров',
    'requestAddNewItems' => 'Добавление новых товаров',
    'requestAddUpdateSC' => 'Добавление новых СЦ/изменение существующих СЦ',
    'requestAddUpdateSizeGrid' => 'Добавление/изменение размерной сетки',
    'requestAddUpdateTags' => 'Добавление/изменение тегов',
    'requestAddUpdateVideo' => 'Добавление/изменение видео',
    'requestCheckHidden' => 'Проверка скрытых товаров',
    'requestGroupItems' => 'Группировка товаров',
    'requestStructureDesign' => 'Проектирование структуры',
    'requestTransferItems' => 'Перенос товаров',
    'requestUpdateAttrOrValues' => 'Изменение существующих параметров/значений',
    'requestUpdateFatPortalCat' => 'Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров',
    'requestUpdateItems' => 'Добавление/изменение информации в существующих товарах',
    'requestUploadPhoto' => 'Заливка фото с фотостудии',
    'massEdit' => 'Пакетное редактирование',
    'requestCreate' => 'Создание задач',
    'requestCreateRelated' => 'Создание подзадач',
    'requestDeleteAttachments' => 'Удаление вложеных файлов',
    'requestUpdate' => 'Обновление полей заявок',
    'requestViewAllRequests' => 'Просмотр всех заявок',
    'requestViewDirectionRequests' => 'Просмотр заявок своего направления',
    'requestViewOwnRequests' => 'Просмотр своих заявок',
    'requestViewTeamRequests' => 'Просмотр заявок команды',
    'takeToWork' => 'Взятие в работу и выполнение/отмена заявок (не менеджером заявки)',
    'viewSplitterModerationRequests' => 'Просмотр заявок отдела модерации',
    'categoryUpdate' => 'Редактирование категорий',
    'coefUpdate' => 'Редактирование коэфициентов',
    'excludedFieldsUpdate' => 'Редактирование взаимоисключающих чекбоксов',
    'fieldsUpdate' => 'Редактирование полей',
    'priorityUpdate' => 'Редактирование приоритетов',
    'reasonsUpdate' => 'Редактирование причин',
    'sellerUpdate' => 'Редактирование магазинов',
    'teamUpdate' => 'Редактирование команд',
    'seeAllTemplates' => 'Просмотр всех шаблонов',
    'seeDirectionTemplates' => 'Просмотр шаблонов направления',
    'seeTeamTemplates' => 'Просмотр шаблонов команды',
    'updateTemplates' => 'Обновление чужих шаблонов',
    'transferCompletedToClosed' => 'Выполнена -> Закрыта',
    'transferCompletedToInWork' => 'Выполнена -> В работе',
    'transferInCheckToDeclined' => 'Готова для распределения -> Отменена',
    'transferInCheckToRequireChange' => 'Готова для распределения -> На доработке',
    'transferInCheckToWaitWork' => 'Готова для распределения -> Ожидает взятия в работу',
    'transferInWorkToCompleted' => 'В работе	-> Выполнена',
    'transferInWorkToDeclined' => 'В работе	-> Отменена',
    'transferInWorkToOnHold' => 'В работе	-> Ожидает (нужны ризоны)',
    'transferInWorkToPartialComplete' => 'В работе	-> Частично выполнена (нужны ризоны)',
    'transferInWorkToWaitWork' => 'В работе -> Ожидает взятия в работу',
    'transferOnHoldToCompleted' => 'Ожидает -> Выполнена',
    'transferOnHoldToInWork' => 'Ожидает (нужны ризоны) -> В работе',
    'transferOnHoldToPartialComplete' => 'Ожидает -> Частично выполнена',
    'transferPartialCompleteToClosed' => 'Частично выполнена -> Закрыта',
    'transferPartialCompleteToInWork' => 'Частично выполнена -> В работе',
    'transferRequireChangeToDeclined' => 'На доработке -> Отменена',
    'transferRequireChangeToWaitCheck' => 'На доработке -> Новая',
    'transferWaitCheckToDeclined' => 'Новая -> Отменена',
    'transferWaitCheckToInCheck' => 'Новые -> Готовы для распределения',
    'transferWaitCheckToRequireChange' => 'Новая -> На доработке',
    'transferWaitCheckToWaitWork' => 'Новая -> Ожидает взятия в работу',
    'transferWaitWorkToDeclined' => 'Ожидает взятия в работу -> Отменена',
    'transferWaitWorkToInWork' => 'Ожидает взятия в работу -> В работе',
    'viewOwnRequestsMrk' => 'Просмотр только своих задач',
    'viewTeamRequestsMrk' => 'Просмотр задач команды',
    'viewAllRequestsMrk' => 'Просмотр всех задач',
    'createFilterMrk' => 'Создание фильтра',
    'createRequestMrk' => 'Создание задач',
    'createSubRequestMrk' => 'Создание подзадач',
    'updateRequestMrk' => 'Редактирование задач',
    'commentRequestMrk' => 'Комментирование задач',
    'id' => 'ID пользователя',
    'name' => 'Имя пользователя',
    'login' => 'Логин пользователя',
    'email' => 'Почта пользователя',
    'parent_id' => 'Руководитель',
    'position' => 'Роль пользователя',
    'status' => 'Cтатус пользователя',
    'create_ts' => 'Дата создания',
    'created_by' => 'ID создателя',
    'change_date' => 'Дата последнего обновления',
    'team' => 'Команда пользователя',
    'drfo' => 'ДРФО',
    'positions' => 'Роли пользователя',
];

return [
    'case1' => [
        'setting' => [
            'description' => 'Получить список пользователей',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'requestParameters' => [],
            'responseBody' => [
                'data' => [
                    'models' => [
                        0 => [
                            'id' => 1,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'В работе	-> Частично выполнена (нужны ризоны)',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-04-17 17:25:38',
                        ],
                        1 => [
                            'id' => 2,
                            'changed_user_id' => 35,
                            'changed_user_login' => 'julia',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Обновление полей заявок',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-20 11:48:15',
                        ],
                        2 => [
                            'id' => 3,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-15 11:13:23',
                        ],
                        3 => [
                            'id' => 4,
                            'changed_user_id' => 32,
                            'changed_user_login' => 'bpm_supervisor_12',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '13',
                            'new_value' => '7',
                            'date' => '2020-04-13 16:15:42',
                        ],
                        4 => [
                            'id' => 5,
                            'changed_user_id' => 5,
                            'changed_user_login' => 'bpm_headSupervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Блокирование пользователей',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-29 13:18:09',
                        ],
                        5 => [
                            'id' => 6,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Редактирование коэфициентов',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-15 09:28:14',
                        ],
                        6 => [
                            'id' => 7,
                            'changed_user_id' => 11,
                            'changed_user_login' => 'bpm_contentManager_1a',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Cтатус пользователя',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-11 13:25:33',
                        ],
                        7 => [
                            'id' => 8,
                            'changed_user_id' => 31,
                            'changed_user_login' => 'bpm_supervisor_11',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '12',
                            'new_value' => '6',
                            'date' => '2020-04-13 16:15:41',
                        ],
                        8 => [
                            'id' => 9,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Выгрузка отчетов по всем пользователям',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-20 10:12:03',
                        ],
                        9 => [
                            'id' => 10,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Создание задач',
                            'old_value' => '1',
                            'new_value' => '0',
                            'date' => '2020-04-17 17:27:57',
                        ],
                        10 => [
                            'id' => 11,
                            'changed_user_id' => 15,
                            'changed_user_login' => 'bpm_teamLead_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Создание задач',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-14 19:08:50',
                        ],
                        11 => [
                            'id' => 12,
                            'changed_user_id' => 4,
                            'changed_user_login' => 'kutsan.k',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Просмотр заявок команды',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-25 11:36:14',
                        ],
                        12 => [
                            'id' => 13,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Редактирование коэфициентов',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-29 13:18:48',
                        ],
                        13 => [
                            'id' => 14,
                            'changed_user_id' => 11,
                            'changed_user_login' => 'bpm_contentManager_1a',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '14',
                            'new_value' => '1',
                            'date' => '2020-05-07 10:47:23',
                        ],
                        14 => [
                            'id' => 15,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Просмотр своих заявок',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-15 10:20:05',
                        ],
                        15 => [
                            'id' => 16,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Создание подзадач',
                            'old_value' => '1',
                            'new_value' => '0',
                            'date' => '2020-05-15 09:34:36',
                        ],
                        16 => [
                            'id' => 17,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'В работе	-> Отменена',
                            'old_value' => '1',
                            'new_value' => '0',
                            'date' => '2020-04-17 17:24:35',
                        ],
                        17 => [
                            'id' => 18,
                            'changed_user_id' => 5,
                            'changed_user_login' => 'bpm_headSupervisor_1',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Роль пользователя',
                            'old_value' => 'admin',
                            'new_value' => 'headSupervisor',
                            'date' => '2020-05-29 13:20:16',
                        ],
                        18 => [
                            'id' => 19,
                            'changed_user_id' => 11,
                            'changed_user_login' => 'bpm_contentManager_1a',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Руководитель',
                            'old_value' => '6. Супервайзер Начальникович 1',
                            'new_value' => '23. Супервайзер Начальникович 3',
                            'date' => '2020-05-14 18:37:52',
                        ],
                        19 => [
                            'id' => 20,
                            'changed_user_id' => 12,
                            'changed_user_login' => 'bpm_contentManager_1b',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Просмотр заявок отдела модерации',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-08 13:04:03',
                        ],
                    ],
                    '_links' => [
                        'self' => [
                            'href' => 'http://lisa.api/user-changing-history/list?page=1',
                        ],
                        'first' => [
                            'href' => 'http://lisa.api/user-changing-history/list?page=1',
                        ],
                        'last' => [
                            'href' => 'http://lisa.api/user-changing-history/list?page=1',
                        ],
                    ],
                    '_meta' => [
                        'totalCount' => 20,
                        'pageCount' => 1,
                        'currentPage' => 1,
                        'perPage' => 20,
                    ],
                ],
                'initialValues' => [
                    'filters' => [
                        'changed_field' => $changed_field,
                    ],
                ],
                'filters' => [
                ],
            ],
        ]
    ],

    'case2' => [
        'setting' => [
            'description' => 'Получить список пользователей с фильтром по id изменённого и сортировкой по id',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'requestParameters' => [
                'filter[changed_user_id]' => '6',
                'sort' => '-id',
            ],
            'responseBody' => [
                'data' => [
                    'models' => [
                        0 => [
                            'id' => 17,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'В работе	-> Отменена',
                            'old_value' => '1',
                            'new_value' => '0',
                            'date' => '2020-04-17 17:24:35',
                        ],
                        1 => [
                            'id' => 10,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Создание задач',
                            'old_value' => '1',
                            'new_value' => '0',
                            'date' => '2020-04-17 17:27:57',
                        ],
                        2 => [
                            'id' => 9,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Выгрузка отчетов по всем пользователям',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-20 10:12:03',
                        ],
                        3 => [
                            'id' => 1,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'В работе	-> Частично выполнена (нужны ризоны)',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-04-17 17:25:38',
                        ],
                    ],
                    '_links' => [
                        'self' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=6&sort=-id&page=1',
                        ],
                        'first' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=6&sort=-id&page=1',
                        ],
                        'last' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=6&sort=-id&page=1',
                        ],
                    ],
                    '_meta' => [
                        'totalCount' => 4,
                        'pageCount' => 1,
                        'currentPage' => 1,
                        'perPage' => 20,
                    ],
                ],
                'initialValues' => [
                    'filters' => [
                        'changed_field' => $changed_field,
                    ],
                ],
                'filters' => [
                    'changed_user_id' => '6',
                ],
            ],
        ]
    ],

    'case3' => [
        'setting' => [
            'description' => 'Получить список пользователей с фильтром по логину изменённого и сортировкой по логину изменившего',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'requestParameters' => [
                'filter[changed_user_id]' => '',
                'filter[changed_user_login]' => 'sup',
                'sort' => 'changer_login',
            ],
            'responseBody' => [
                'data' => [
                    'models' => [
                        0 => [
                            'id' => 8,
                            'changed_user_id' => 31,
                            'changed_user_login' => 'bpm_supervisor_11',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '12',
                            'new_value' => '6',
                            'date' => '2020-04-13 16:15:41',
                        ],
                        1 => [
                            'id' => 4,
                            'changed_user_id' => 32,
                            'changed_user_login' => 'bpm_supervisor_12',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '13',
                            'new_value' => '7',
                            'date' => '2020-04-13 16:15:42',
                        ],
                        2 => [
                            'id' => 18,
                            'changed_user_id' => 5,
                            'changed_user_login' => 'bpm_headSupervisor_1',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Роль пользователя',
                            'old_value' => 'admin',
                            'new_value' => 'headSupervisor',
                            'date' => '2020-05-29 13:20:16',
                        ],
                        3 => [
                            'id' => 10,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Создание задач',
                            'old_value' => '1',
                            'new_value' => '0',
                            'date' => '2020-04-17 17:27:57',
                        ],
                        4 => [
                            'id' => 17,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'В работе	-> Отменена',
                            'old_value' => '1',
                            'new_value' => '0',
                            'date' => '2020-04-17 17:24:35',
                        ],
                        5 => [
                            'id' => 9,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Выгрузка отчетов по всем пользователям',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-20 10:12:03',
                        ],
                        6 => [
                            'id' => 5,
                            'changed_user_id' => 5,
                            'changed_user_login' => 'bpm_headSupervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Блокирование пользователей',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-29 13:18:09',
                        ],
                        7 => [
                            'id' => 1,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'В работе	-> Частично выполнена (нужны ризоны)',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-04-17 17:25:38',
                        ],
                    ],
                    '_links' => [
                        'self' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=sup&sort=changer_login&page=1',
                        ],
                        'first' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=sup&sort=changer_login&page=1',
                        ],
                        'last' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=sup&sort=changer_login&page=1',
                        ],
                    ],
                    '_meta' => [
                        'totalCount' => 8,
                        'pageCount' => 1,
                        'currentPage' => 1,
                        'perPage' => 20,
                    ],
                ],
                'initialValues' => [
                    'filters' => [
                        'changed_field' => $changed_field,
                    ],
                ],
                'filters' => [
                    'changed_user_id' => '',
                    'changed_user_login' => 'sup',
                ],
            ],
        ]
    ],

    'case4' => [
        'setting' => [
            'description' => 'Получить список пользователей с фильтром по изменённому полю и сортировкой по дате',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'requestParameters' => [
                'filter[changed_user_id]' => '',
                'filter[changed_user_login]' => '',
                'filter[changed_field]' => 'team',
                'sort' => '-date',
            ],
            'responseBody' => [
                'data' => [
                    'models' => [
                        0 => [
                            'id' => 12,
                            'changed_user_id' => 4,
                            'changed_user_login' => 'kutsan.k',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Просмотр заявок команды',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-25 11:36:14',
                        ],
                        1 => [
                            'id' => 14,
                            'changed_user_id' => 11,
                            'changed_user_login' => 'bpm_contentManager_1a',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '14',
                            'new_value' => '1',
                            'date' => '2020-05-07 10:47:23',
                        ],
                        2 => [
                            'id' => 4,
                            'changed_user_id' => 32,
                            'changed_user_login' => 'bpm_supervisor_12',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '13',
                            'new_value' => '7',
                            'date' => '2020-04-13 16:15:42',
                        ],
                        3 => [
                            'id' => 8,
                            'changed_user_id' => 31,
                            'changed_user_login' => 'bpm_supervisor_11',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Команда пользователя',
                            'old_value' => '12',
                            'new_value' => '6',
                            'date' => '2020-04-13 16:15:41',
                        ],
                    ],
                    '_links' => [
                        'self' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=&filter%5Bchanged_field%5D=team&sort=-date&page=1',
                        ],
                        'first' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=&filter%5Bchanged_field%5D=team&sort=-date&page=1',
                        ],
                        'last' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=&filter%5Bchanged_field%5D=team&sort=-date&page=1',
                        ],
                    ],
                    '_meta' => [
                        'totalCount' => 4,
                        'pageCount' => 1,
                        'currentPage' => 1,
                        'perPage' => 20,
                    ],
                ],
                'initialValues' => [
                    'filters' => [
                        'changed_field' => $changed_field,
                    ],
                ],
                'filters' => [
                    'changed_user_id' => '',
                    'changed_user_login' => '',
                    'changed_field' => 'team',
                ],
            ],
        ]
    ],

    'case5' => [
        'setting' => [
            'description' => 'Получить список пользователей с фильтрами по новому и старому значению и сортировкой по id изменившего',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'requestParameters' => [
                'filter[changed_user_id]' => '',
                'filter[changed_user_login]' => '',
                'filter[changed_field]' => '',
                'filter[new_value]' => '1',
                'sort' => '-changer_id',
                'filter[old_value]' => '0',
            ],
            'responseBody' => [
                'data' => [
                    'models' => [
                        0 => [
                            'id' => 13,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 5,
                            'changer_login' => 'bpm_headSupervisor_1',
                            'changed_field' => 'Редактирование коэфициентов',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-29 13:18:48',
                        ],
                        1 => [
                            'id' => 2,
                            'changed_user_id' => 35,
                            'changed_user_login' => 'julia',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Обновление полей заявок',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-20 11:48:15',
                        ],
                        2 => [
                            'id' => 3,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-15 11:13:23',
                        ],
                        3 => [
                            'id' => 5,
                            'changed_user_id' => 5,
                            'changed_user_login' => 'bpm_headSupervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Блокирование пользователей',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-29 13:18:09',
                        ],
                        4 => [
                            'id' => 6,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Редактирование коэфициентов',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-15 09:28:14',
                        ],
                        5 => [
                            'id' => 7,
                            'changed_user_id' => 11,
                            'changed_user_login' => 'bpm_contentManager_1a',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Cтатус пользователя',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-11 13:25:33',
                        ],
                        6 => [
                            'id' => 9,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Выгрузка отчетов по всем пользователям',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-03-20 10:12:03',
                        ],
                        7 => [
                            'id' => 11,
                            'changed_user_id' => 15,
                            'changed_user_login' => 'bpm_teamLead_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Создание задач',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-14 19:08:50',
                        ],
                        8 => [
                            'id' => 12,
                            'changed_user_id' => 4,
                            'changed_user_login' => 'kutsan.k',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Просмотр заявок команды',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-25 11:36:14',
                        ],
                        9 => [
                            'id' => 15,
                            'changed_user_id' => 17,
                            'changed_user_login' => 'bpm_productManager_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Просмотр своих заявок',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-15 10:20:05',
                        ],
                        10 => [
                            'id' => 1,
                            'changed_user_id' => 6,
                            'changed_user_login' => 'bpm_supervisor_1',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'В работе	-> Частично выполнена (нужны ризоны)',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-04-17 17:25:38',
                        ],
                        11 => [
                            'id' => 20,
                            'changed_user_id' => 12,
                            'changed_user_login' => 'bpm_contentManager_1b',
                            'changer_id' => 4,
                            'changer_login' => 'kutsan.k',
                            'changed_field' => 'Просмотр заявок отдела модерации',
                            'old_value' => '0',
                            'new_value' => '1',
                            'date' => '2020-05-08 13:04:03',
                        ],
                    ],
                    '_links' => [
                        'self' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=&filter%5Bchanged_field%5D=&filter%5Bnew_value%5D=1&filter%5Bold_value%5D=0&sort=-changer_id&page=1',
                        ],
                        'first' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=&filter%5Bchanged_field%5D=&filter%5Bnew_value%5D=1&filter%5Bold_value%5D=0&sort=-changer_id&page=1',
                        ],
                        'last' => [
                            'href' => 'http://lisa.api/user-changing-history/list?filter%5Bchanged_user_id%5D=&filter%5Bchanged_user_login%5D=&filter%5Bchanged_field%5D=&filter%5Bnew_value%5D=1&filter%5Bold_value%5D=0&sort=-changer_id&page=1',
                        ],
                    ],
                    '_meta' => [
                        'totalCount' => 12,
                        'pageCount' => 1,
                        'currentPage' => 1,
                        'perPage' => 20,
                    ],
                ],
                'initialValues' => [
                    'filters' => [
                        'changed_field' => $changed_field,
                    ],
                ],
                'filters' => [
                    'changed_user_id' => '',
                    'changed_user_login' => '',
                    'changed_field' => '',
                    'new_value' => '1',
                    'old_value' => '0',
                ],
            ],
        ]
    ],

];
