<?php

return [
    'case1' => [
        'setting' => [
            'description' => 'Изменения статусов нотификаций и переход в их настройки',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'db_1' => [
                "lisa_fixtures" => [
                    'user_notifications' => [
                        [
                            "id" => 1,
                            "user_id" => 4,
                            "notification" => '',
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 2,
                            "user_id" => 6,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 3,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 4,
                            "user_id" => 15,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 5,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 6,
                            "user_id" => 17,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ]
                    ],
                ],
            ],
            'db_2' => [
                "lisa_fixtures" => [
                    'user_notifications' => [
                        [
                            "id" => 1,
                            "user_id" => 4,
                            "notification" => '',
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 2,
                            "user_id" => 6,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 3,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 4,
                            "user_id" => 15,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 5,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 6,
                            "user_id" => 17,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ]
                    ],
                ],
            ],
            'db_3' => [
                "lisa_fixtures" => [
                    'user_notifications' => [
                        [
                            "id" => 1,
                            "user_id" => 4,
                            "notification" => '',
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 2,
                            "user_id" => 6,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 3,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 4,
                            "user_id" => 15,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 5,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 6,
                            "user_id" => 17,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ]
                    ],
                ],
            ],
            'db_4' => [
                "lisa_fixtures" => [
                    'user_notifications' => [
                        [
                            "id" => 1,
                            "user_id" => 4,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 2,
                            "user_id" => 6,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 3,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 4,
                            "user_id" => 15,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 5,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 6,
                            "user_id" => 17,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ]
                    ],
                ],
            ],
            'db_5' => [
                "lisa_fixtures" => [
                    'user_notifications' => [
                        [
                            "id" => 1,
                            "user_id" => 4,
                            "notification" => '',
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 2,
                            "user_id" => 6,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 3,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 4,
                            "user_id" => 15,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 5,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 6,
                            "user_id" => 17,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ]
                    ],
                ],
            ],
            'db_6' => [
                "lisa_fixtures" => [
                    'user_notifications' => [
                        [
                            "id" => 1,
                            "user_id" => 4,
                            "notification" => '',
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 2,
                            "user_id" => 6,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 3,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 4,
                            "user_id" => 15,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 5,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 6,
                            "user_id" => 17,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ]
                    ],
                ],
            ],
            'db_7' => [
                "lisa_fixtures" => [
                    'user_notifications' => [
                        [
                            "id" => 1,
                            "user_id" => 4,
                            "notification" => '',
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 2,
                            "user_id" => 6,
                            "notification" => '',
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Причина": "Другое (описан в коментариях) | Нада </b>!@#$%^&*()_+`-]\'/[;.,}\"?{:>\\\|абвгдеёжзийклмнопрстуфхцчшщъыьэюяєґїіАБВГДЕЁЖЗИЙКЛМНО"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "3", "oldValue": 1}'
                        ],
                        [
                            "id" => 3,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 4,
                            "user_id" => 15,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => "[]",
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "7", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 5,
                            "user_id" => 4,
                            "notification" => "",
                            "status" => 1,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ],
                        [
                            "id" => 6,
                            "user_id" => 17,
                            "notification" => "",
                            "status" => 0,
                            "created_at" => date("Y-m-d"),
                            "request_id" => 1,
                            "priority" => 2,
                            "amount_to_work" => 10,
                            "request_subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                            "fields_for_complete" => '{"Вид структуры": "(не указан)", "Ручная загрузка": "Да", "Пакетная загрузка": "(не указан)", "Сложность структуры": "(не указан)", "Коэффициент типа задачи": "0.5", "Общее количество ошибок": "0", "Уровень сложности задачи": "(не указан)", "Количество изменённых товаров": "(не указан)", "Общее количество товаров с ошибками": "0", "Коэффициент уровня сложности задачи": "1"}',
                            "triggered_by" => "Константин Куцан",
                            "event" => "status",
                            "changed_fields" => '{"newValue": "8", "oldValue": 6}',
                            "notify_service_id" => null
                        ]
                    ],
                ],
            ],
        ]
    ],
];
