<?php

return [
    'case1' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление новых товаров (Работа с товарами Розетки)',
            'type' => 1,
            'direction' => 1
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Добавление товаров в новую категорию',
                ' Лоты',
                ' На основе отзыва клиента на сайте',
                ' Пакетная загрузка',
                ' Промо-описание',
                ' Ручная загрузка',
                ' С видео',
                ' С размерной сеткой',
                ' С тегами к товарам',
                ' С фотосъемкой',
                ' Уценка',
                ' Уценка 2'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "RequestFields[8]" => 1,
                "RequestFields[9]" => 1,
                "RequestFields[15]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 1,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 5,
                "Request[subject]" => "Добавление новых товаров (Работа с товарами Розетки)",
                "Request[type_id]" => 1,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
                "_csrf-backend" => null
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 1,
                    "supervisor_id" => 4,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 5,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case2' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление новых товаров (Работа с товарами Маркетплейса)',
            'type' => 1,
            'direction' => 2
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Автомодерация',
                ' БУ, REF',
                ' Жалоба на товар продавца маркета',
                ' С видео',
                ' С палитрой',
                ' С размерной сеткой'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[8]" => 1,
                "RequestFields[15]" => 1,
                "RequestFields[19]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[seller_id]" => 0,
                "Request[description]" => "description",
                "Request[direction]" => 2,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление новых товаров (Работа с товарами Маркетплейса)",
                "Request[type_id]" => 1,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
                "_csrf-backend" => null
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 1,
                    "supervisor_id" => 5,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 2,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых товаров (Работа с товарами Маркетплейса)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => null,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 2,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],
                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 19,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 114,
                        'value' => 3,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case3' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление/изменение информации в существующих товарах (Работа с товарами Розетки)',
            'type' => 2,
            'direction' => 1
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Добавление/обновление инструкций',
                ' На основе отзыва клиента на сайте',
                ' Обновление описания',
                ' Обновление фото',
                ' Обновление характеристик',
                ' Пакетная загрузка',
                ' Промо-описание',
                ' Ручная загрузка',
                ' С видео',
                ' С размерной сеткой',
                ' С тегами к товарам',
                ' С фотосъемкой',
                ' Уценка',
                ' Уценка 2'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "RequestFields[8]" => 1,
                "RequestFields[9]" => 1,
                "RequestFields[15]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 1,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 5,
                "Request[subject]" => "Добавление/изменение информации в существующих товарах (Работа с товарами Розетки)",
                "Request[type_id]" => 2,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 2,
                    "supervisor_id" => 4,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление/изменение информации в существующих товарах (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 5,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 0.1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case4' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление/изменение информации в существующих товарах (Работа с товарами Маркетплейса)',
            'type' => 2,
            'direction' => 2
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Автомодерация',
                ' БУ, REF',
                ' Жалоба на товар продавца маркета',
                ' С видео',
                ' С палитрой',
                ' С размерной сеткой'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[8]" => 1,
                "RequestFields[15]" => 1,
                "RequestFields[19]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[seller_id]" => 0,
                "Request[description]" => "description",
                "Request[direction]" => 2,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление/изменение информации в существующих товарах (Работа с товарами Маркетплейса)",
                "Request[type_id]" => 2,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 2,
                    "supervisor_id" => 5,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 2,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление/изменение информации в существующих товарах (Работа с товарами Маркетплейса)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => null,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 2,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 19,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 114,
                        'value' => 3,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case5' => [
        'settings' => [
            'description' => 'Новая заявка на Перенос товаров (Работа с товарами Розетки)',
            'type' => 3,
            'direction' => 1
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Добавление товаров в новую категорию',
                ' Лоты',
                ' На основе отзыва клиента на сайте',
                ' Пакетная загрузка',
                ' Промо-описание',
                ' Ручная загрузка',
                ' С видео',
                ' С размерной сеткой',
                ' С тегами к товарам',
                ' С фотосъемкой',
                ' Уценка',
                ' Уценка 2'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "RequestFields[8]" => 1,
                "RequestFields[9]" => 1,
                "RequestFields[15]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 1,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 5,
                "Request[subject]" => "Перенос товаров (Работа с товарами Розетки)",
                "Request[type_id]" => 3,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 3,
                    "supervisor_id" => 4,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Перенос товаров (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 5,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 0.75,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case6' => [
        'settings' => [
            'description' => 'Новая заявка на Перенос товаров (Работа с товарами Маркетплейса)',
            'type' => 3,
            'direction' => 2
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Автомодерация',
                ' БУ, REF',
                ' Жалоба на товар продавца маркета',
                ' С видео',
                ' С палитрой',
                ' С размерной сеткой'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[8]" => 1,
                "RequestFields[15]" => 1,
                "RequestFields[19]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[seller_id]" => 0,
                "Request[description]" => "description",
                "Request[direction]" => 2,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Перенос товаров (Работа с товарами Маркетплейса)",
                "Request[type_id]" => 3,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 3,
                    "supervisor_id" => 5,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 2,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Перенос товаров (Работа с товарами Маркетплейса)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => null,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 2,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 19,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 114,
                        'value' => 3,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case7' => [
        'settings' => [
            'description' => 'Новая заявка на Группировка товаров (Определяется типом задачи)',
            'type' => 4,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Пакетная загрузка',
                ' Ручная загрузка',
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Группировка товаров (Определяется типом задачи)",
                "Request[type_id]" => 4,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 4,
                    "supervisor_id" => 30,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Группировка товаров (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 4,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 0.5,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 61,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case8' => [
        'settings' => [
            'description' => 'Новая заявка на Заливка фото с фотостудии (Работа с товарами Розетки)',
            'type' => 5,
            'direction' => 1
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Добавление товаров в новую категорию',
                ' Лоты',
                ' На основе отзыва клиента на сайте',
                ' Пакетная загрузка',
                ' Промо-описание',
                ' Ручная загрузка',
                ' С видео',
                ' С размерной сеткой',
                ' С тегами к товарам',
                ' С фотосъемкой',
                ' Уценка',
                ' Уценка 2'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "RequestFields[8]" => 1,
                "RequestFields[9]" => 1,
                "RequestFields[15]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 1,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 5,
                "Request[subject]" => "Заливка фото с фотостудии (Работа с товарами Розетки)",
                "Request[type_id]" => 5,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 5,
                    "supervisor_id" => 4,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Заливка фото с фотостудии (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 5,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case9' => [
        'settings' => [
            'description' => 'Новая заявка на Проверка скрытых товаров (Работа с товарами Маркетплейса)',
            'type' => 6,
            'direction' => 2
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Автомодерация',
                ' БУ, REF',
                ' Жалоба на товар продавца маркета',
                ' С видео',
                ' С палитрой',
                ' С размерной сеткой'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[8]" => 1,
                "RequestFields[15]" => 1,
                "RequestFields[19]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[seller_id]" => 0,
                "Request[description]" => "description",
                "Request[direction]" => 2,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Проверка скрытых товаров (Работа с товарами Маркетплейса)",
                "Request[type_id]" => 6,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 6,
                    "supervisor_id" => 5,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 2,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Проверка скрытых товаров (Работа с товарами Маркетплейса)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => null,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 2,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 19,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 114,
                        'value' => 3,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case10' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление нового портала/раздела фат-меню/категории товаров (Определяется типом задачи)',
            'type' => 7,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Добавление графики',
                ' Пакетная загрузка',
                ' Ручная загрузка',
                ' Точки входа'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление нового портала/раздела фат-меню/категории товаров (Определяется типом задачи)",
                "Request[type_id]" => 7,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 7,
                    "supervisor_id" => 35,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление нового портала/раздела фат-меню/категории товаров (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 6,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 55,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case11' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров (Определяется типом задачи)',
            'type' => 8,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Добавление графики',
                ' Пакетная загрузка',
                ' Ручная загрузка',
                ' Точки входа'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров (Определяется типом задачи)",
                "Request[type_id]" => 8,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 8,
                    "supervisor_id" => 35,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 6,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 55,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case12' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление параметров/значений (Определяется типом задачи)',
            'type' => 9,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Пакетная загрузка',
                ' Ручная загрузка',
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление параметров/значений (Определяется типом задачи)",
                "Request[type_id]" => 9,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 9,
                    "supervisor_id" => 34,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление параметров/значений (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 5,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 59,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case13' => [
        'settings' => [
            'description' => 'Новая заявка на Изменение существующих параметров/значений (Определяется типом задачи)',
            'type' => 10,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Пакетная загрузка',
                ' Ручная загрузка',
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Изменение существующих параметров/значений (Определяется типом задачи)",
                "Request[type_id]" => 10,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 10,
                    "supervisor_id" => 34,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Изменение существующих параметров/значений (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 5,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 59,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case14' => [
        'settings' => [
            'description' => 'Новая заявка на Проектирование структуры (Определяется типом задачи)',
            'type' => 11,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Пакетная загрузка',
                ' Ручная загрузка',
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Проектирование структуры (Определяется типом задачи)",
                "Request[type_id]" => 11,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 11,
                    "supervisor_id" => 34,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Проектирование структуры (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 5,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 59,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case15' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление новых СЦ/изменение существующих СЦ (Работа с товарами Розетки)',
            'type' => 12,
            'direction' => 1
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Добавление товаров в новую категорию',
                ' Лоты',
                ' На основе отзыва клиента на сайте',
                ' Пакетная загрузка',
                ' Промо-описание',
                ' Ручная загрузка',
                ' С видео',
                ' С размерной сеткой',
                ' С тегами к товарам',
                ' С фотосъемкой',
                ' Уценка',
                ' Уценка 2'
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "RequestFields[8]" => 1,
                "RequestFields[9]" => 1,
                "RequestFields[15]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 1,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 5,
                "Request[subject]" => "Добавление новых СЦ/изменение существующих СЦ (Работа с товарами Розетки)",
                "Request[type_id]" => 12,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 12,
                    "supervisor_id" => 4,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых СЦ/изменение существующих СЦ (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 5,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case16' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление/изменение видео (Определяется типом задачи)',
            'type' => 13,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Пакетная загрузка',
                ' Ручная загрузка',
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление/изменение видео (Определяется типом задачи)",
                "Request[type_id]" => 13,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 13,
                    "supervisor_id" => 35,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление/изменение видео (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 6,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 56,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case17' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление/изменение размерной сетки (Определяется типом задачи)',
            'type' => 14,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Пакетная загрузка',
                ' Ручная загрузка',
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление/изменение размерной сетки (Определяется типом задачи)",
                "Request[type_id]" => 14,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 14,
                    "supervisor_id" => 35,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление/изменение размерной сетки (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 6,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 57,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case18' => [
        'settings' => [
            'description' => 'Новая заявка на Добавление/изменение тегов (Определяется типом задачи)',
            'type' => 15,
            'direction' => 0
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'checkboxes' => [
                ' Пакетная загрузка',
                ' Ручная загрузка',
            ],
            'requestURL' => '/bpm/request/create',
            'requestBody' => [
                "RequestFields[1]" => 1,
                "Request[amount_to_work]" => 10,
                "Request[attachment_folder]" => '18ac118ec8919dcb3ad0d7ddd129d88a',
                "Request[addedAttachments]" => '[]',
                "Request[deletedAttachments]" => '[]',
                "Request[attachments]" => '[]',
                "Request[category_id]" => 1,
                "Request[description]" => "description",
                "Request[direction]" => 0,
                "Request[parent_id]" => null,
                "Request[planned_finish_date]" => null,
                "Request[priority]" => 2,
                "Request[seller_id]" => 0,
                "Request[subject]" => "Добавление/изменение тегов (Определяется типом задачи)",
                "Request[type_id]" => 15,
                "Request[uploadedFiles][]" => null,
                "Request[uploadedFiles][]" => null,
            ],
            'responseCode' => 200,
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 15,
                    "supervisor_id" => 35,
                    "manager_id" => null,
                    "status" => 1,
                    "direction" => 0,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    //"created_at" => '2020-01-01 00:00:01',
                    "correction_comment" => null,
                    "amount_to_work" => 10,
                    "subject" => "Добавление/изменение тегов (Определяется типом задачи)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 0,
                    "recommendations" => null,
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => null,
                    "actual_finish_date" => null,
                    "supervisor_process_date" => null,
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => null,
                    "supervisor_comment" => null,
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 6,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => null,
                ],

                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 58,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ]
];
