<?php

use lisa\Constants;

return [
    'data' => [
        'models' => [
            0 => [
                'id' => 19,
                'name' => 'Сео Сеошевич 1',
                'login' => 'bpm_seo_1',
                'email' => 'bpm_seo_1@rozetka.com.ua',
                'team' => 19,
                'teamName' => 'SEO-отдел',
                'parent_id' => 4,
                'position' => 'seo',
                'positions' => '["seo"]',
                'positionName' => 'Сотрудник seo-отдела (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:37',
                'created_by' => 1,
                'change_date' => '2020-06-25 13:18:41',
                'drfo' => '\'000000018',
                'parent' => '4.Константин Куцан',
            ],
            1 => [
                'id' => 16,
                'name' => 'Тим Лидович 2',
                'login' => 'bpm_teamLead_2',
                'email' => 'bpm_teamLead_2@rozetka.com.ua',
                'team' => 18,
                'teamName' => 'Маркетплейс (инициаторы)',
                'parent_id' => 4,
                'position' => 'teamLead',
                'positions' => '["teamLead"]',
                'positionName' => 'Руководитель направления (тимлид) (Все)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:36',
                'created_by' => 1,
                'change_date' => '2020-06-25 10:49:20',
                'drfo' => '\'000000016',
                'parent' => '4.Константин Куцан',
            ],
            2 => [
                'id' => 18,
                'name' => 'Менеджер Продактович 2',
                'login' => 'bpm_productManager_2',
                'email' => 'bpm_productManager_2@rozetka.com.ua',
                'team' => 18,
                'teamName' => 'Маркетплейс (инициаторы)',
                'parent_id' => 4,
                'position' => 'productManager',
                'positions' => '["productManager"]',
                'positionName' => 'Продакт-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:36',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:41:05',
                'drfo' => '\'000000018',
                'parent' => '4.Константин Куцан',
            ],
            3 => [
                'id' => 17,
                'name' => 'Менеджер Продактович 1',
                'login' => 'bpm_productManager_1',
                'email' => 'bpm_productManager_1@rozetka.com.ua',
                'team' => 18,
                'teamName' => 'Маркетплейс (инициаторы)',
                'parent_id' => 4,
                'position' => 'productManager',
                'positions' => '["productManager"]',
                'positionName' => 'Продакт-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:36',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:41:00',
                'drfo' => '\'000000017',
                'parent' => '4.Константин Куцан',
            ],
            4 => [
                'id' => 14,
                'name' => 'Менеджер Контентович 2Б',
                'login' => 'bpm_contentManager_2b',
                'email' => 'bpm_contentManager_2b@rozetka.com.ua',
                'team' => 7,
                'teamName' => 'Маркетплейс Freelance',
                'parent_id' => 10,
                'position' => 'contentManager',
                'positions' => '["contentManager"]',
                'positionName' => 'Контент-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:35',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:40:31',
                'drfo' => '\'000000014',
                'parent' => '10.Супервайзер Начальникович 2',
            ],
            5 => [
                'id' => 13,
                'name' => 'Менеджер Контентович 2А',
                'login' => 'bpm_contentManager_2a',
                'email' => 'bpm_contentManager_2a@rozetka.com.ua',
                'team' => 7,
                'teamName' => 'Маркетплейс Freelance',
                'parent_id' => 10,
                'position' => 'contentManager',
                'positions' => '["contentManager"]',
                'positionName' => 'Контент-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:35',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:40:25',
                'drfo' => '\'000000013',
                'parent' => '10.Супервайзер Начальникович 2',
            ],
            6 => [
                'id' => 12,
                'name' => 'Менеджер Контентович 1Б',
                'login' => 'bpm_contentManager_1b',
                'email' => 'bpm_contentManager_1b@rozetka.com.ua',
                'team' => 1,
                'teamName' => 'Маркетплейс 1',
                'parent_id' => 6,
                'position' => 'contentManager',
                'positions' => '["contentManager"]',
                'positionName' => 'Контент-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-05-19 13:36:23',
                'created_by' => 1,
                'change_date' => '2020-05-19 16:36:23',
                'drfo' => '\'000000012',
                'parent' => '6.Супервайзер Начальникович 1',
            ],
            7 => [
                'id' => 11,
                'name' => 'Менеджер Контентович 1А',
                'login' => 'bpm_contentManager_1a',
                'email' => 'bpm_contentManager_1a@rozetka.com.ua',
                'team' => 1,
                'teamName' => 'Маркетплейс 1',
                'parent_id' => 6,
                'position' => 'contentManager',
                'positions' => '["contentManager"]',
                'positionName' => 'Контент-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-05-19 13:36:23',
                'created_by' => 1,
                'change_date' => '2020-05-19 16:36:23',
                'drfo' => '\'000000011',
                'parent' => '6.Супервайзер Начальникович 1',
            ],
            8 => [
                'id' => 10,
                'name' => 'Супервайзер Начальникович 2',
                'login' => 'bpm_supervisor_2',
                'email' => 'bpm_supervisor_2@rozetka.com.ua',
                'team' => 7,
                'teamName' => 'Маркетплейс Freelance',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-05-19 13:36:23',
                'created_by' => 1,
                'change_date' => '2020-05-19 16:36:22',
                'drfo' => '\'000000010',
                'parent' => '5.Супервайзер Руководько 1',
            ],
        ],
        '_links' => [
            'self' => [
                'href' => 'http://lisa.api/user/list?filter%5Bstatus%5D=1&filter%5Bdrfo%5D=01&sort=-change_date&page=1&per-page=50',
            ],
            'first' => [
                'href' => 'http://lisa.api/user/list?filter%5Bstatus%5D=1&filter%5Bdrfo%5D=01&sort=-change_date&page=1&per-page=50',
            ],
            'last' => [
                'href' => 'http://lisa.api/user/list?filter%5Bstatus%5D=1&filter%5Bdrfo%5D=01&sort=-change_date&page=1&per-page=50',
            ],
        ],
        '_meta' => [
            'totalCount' => 9,
            'pageCount' => 1,
            'currentPage' => 1,
            'perPage' => 50,
        ],
    ],
    'filters' => [
        'status' => '1',
        'drfo' => '01',
    ],
    'initialValues' => [
        'activeTeams' => Constants::ACTIVE_TEAMS,
        'positions' => Constants::POSITIONS,
        'teams' => Constants::ALL_TEAMS,
        'userNames' => Constants::USER_NAMES,
    ]
];