<?php

use lisa\UsersTester;

return [
    'data' => [
        'models' => [
            0 => [
                'id' => 38,
                'name' => 'Супервайзер Категоркин 18',
                'login' => 'bpm_supervisor_18',
                'email' => 'bpm_supervisor_18@rozetka.com.ua',
                'team' => 16,
                'teamName' => 'Изменения в категориях',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:46',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:44:36',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            1 => [
                'id' => 37,
                'name' => 'Супервайзер Проектенко 17',
                'login' => 'bpm_supervisor_17',
                'email' => 'bpm_supervisor_17@rozetka.com.ua',
                'team' => 15,
                'teamName' => 'Проектирование структур категорий + фильтры',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:45',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:44:32',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            2 => [
                'id' => 36,
                'name' => 'Супервайзер Групповушкин 16',
                'login' => 'bpm_supervisor_16',
                'email' => 'bpm_supervisor_16@rozetka.com.ua',
                'team' => 14,
                'teamName' => 'Группировка товаров',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:45',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:44:28',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            3 => [
                'id' => 35,
                'name' => 'Супервайзер Категоркин 15',
                'login' => 'bpm_supervisor_15',
                'email' => 'bpm_supervisor_15@rozetka.com.ua',
                'team' => 16,
                'teamName' => 'Изменения в категориях',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:44',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:44:10',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            4 => [
                'id' => 34,
                'name' => 'Супервайзер Проектенко 14',
                'login' => 'bpm_supervisor_14',
                'email' => 'bpm_supervisor_14@rozetka.com.ua',
                'team' => 15,
                'teamName' => 'Проектирование структур категорий + фильтры',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:44',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:44:05',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            5 => [
                'id' => 33,
                'name' => 'Супервайзер Групповушкин 13',
                'login' => 'bpm_supervisor_13',
                'email' => 'bpm_supervisor_13@rozetka.com.ua',
                'team' => 14,
                'teamName' => 'Группировка товаров',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:43',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:44:01',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            6 => [
                'id' => 32,
                'name' => 'Супервайзер Начальникович 12',
                'login' => 'bpm_supervisor_12',
                'email' => 'bpm_supervisor_12@rozetka.com.ua',
                'team' => 13,
                'teamName' => 'Rozetka Freelance',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:42',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:43:44',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            7 => [
                'id' => 31,
                'name' => 'Супервайзер Начальникович 11',
                'login' => 'bpm_supervisor_11',
                'email' => 'bpm_supervisor_11@rozetka.com.ua',
                'team' => 12,
                'teamName' => 'Спорт и туризм, Автотовары',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:42',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:43:39',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            8 => [
                'id' => 30,
                'name' => 'Супервайзер Начальникович 10',
                'login' => 'bpm_supervisor_10',
                'email' => 'bpm_supervisor_10@rozetka.com.ua',
                'team' => 11,
                'teamName' => 'Бытовая техника, сантехника',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:41',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:43:35',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            9 => [
                'id' => 29,
                'name' => 'Супервайзер Начальникович 9',
                'login' => 'bpm_supervisor_9',
                'email' => 'bpm_supervisor_9@rozetka.com.ua',
                'team' => 10,
                'teamName' => 'IT, Аксесуари, Уценка',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:41',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:43:30',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            10 => [
                'id' => 28,
                'name' => 'Супервайзер Начальникович 8',
                'login' => 'bpm_supervisor_8',
                'email' => 'bpm_supervisor_8@rozetka.com.ua',
                'team' => 9,
                'teamName' => 'FMCG, Косметика и парфюмерия',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:40',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:43:24',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            11 => [
                'id' => 27,
                'name' => 'Супервайзер Начальникович 7',
                'login' => 'bpm_supervisor_7',
                'email' => 'bpm_supervisor_7@rozetka.com.ua',
                'team' => 8,
                'teamName' => 'Fashion',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:40',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:42:52',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            12 => [
                'id' => 26,
                'name' => 'Супервайзер Начальникович 6',
                'login' => 'bpm_supervisor_6',
                'email' => 'bpm_supervisor_6@rozetka.com.ua',
                'team' => 4,
                'teamName' => 'Маркетплейс 4',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:39',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:42:47',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            13 => [
                'id' => 25,
                'name' => 'Супервайзер Начальникович 5',
                'login' => 'bpm_supervisor_5',
                'email' => 'bpm_supervisor_5@rozetka.com.ua',
                'team' => 3,
                'teamName' => 'Маркетплейс 3',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:39',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:42:43',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            14 => [
                'id' => 24,
                'name' => 'Супервайзер Начальникович 4',
                'login' => 'bpm_supervisor_4',
                'email' => 'bpm_supervisor_4@rozetka.com.ua',
                'team' => 2,
                'teamName' => 'Маркетплейс 2',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:38',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:42:39',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            15 => [
                'id' => 23,
                'name' => 'Супервайзер Начальникович 3',
                'login' => 'bpm_supervisor_3',
                'email' => 'bpm_supervisor_3@rozetka.com.ua',
                'team' => 9,
                'teamName' => 'FMCG, Косметика и парфюмерия',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:37',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:42:34',
                'drfo' => '0',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            16 => [
                'id' => 10,
                'name' => 'Супервайзер Начальникович 2',
                'login' => 'bpm_supervisor_2',
                'email' => 'bpm_supervisor_2@rozetka.com.ua',
                'team' => 7,
                'teamName' => 'Маркетплейс Freelance',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-05-19 13:36:23',
                'created_by' => 1,
                'change_date' => '2020-05-19 16:36:22',
                'drfo' => '\'000000010',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            17 => [
                'id' => 6,
                'name' => 'Супервайзер Начальникович 1',
                'login' => 'bpm_supervisor_1',
                'email' => 'bpm_supervisor_1@rozetka.com.ua',
                'team' => 1,
                'teamName' => 'Маркетплейс 1',
                'parent_id' => 5,
                'position' => 'supervisor',
                'positions' => '["supervisor"]',
                'positionName' => 'Супервайзер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-05-19 13:36:22',
                'created_by' => 1,
                'change_date' => '2020-05-19 16:36:22',
                'drfo' => '\'000000006',
                'parent' => '5.Супервайзер Руководько 1',
            ],
            18 => [
                'id' => 5,
                'name' => 'Супервайзер Руководько 1',
                'login' => 'bpm_headSupervisor_1',
                'email' => 'bpm_headSupervisor_1@rozetka.com.ua',
                'team' => 17,
                'teamName' => 'Административная команда',
                'parent_id' => 4,
                'position' => 'headSupervisor',
                'positions' => '["headSupervisor"]',
                'positionName' => 'Руководитель супервайзеров (Все)',
                'status' => 'Активный',
                'create_ts' => '2020-05-19 13:36:22',
                'created_by' => 1,
                'change_date' => '2020-05-19 16:36:22',
                'drfo' => '\'000000005',
                'parent' => '4.Константин Куцан',
            ],
        ],
        '_links' => [
            'self' => [
                'href' => 'http://lisa.api/user/list?sort=-id&filter%5Bname%5D=%D1%81%D1%83%D0%BF&page=1&per-page=50',
            ],
            'first' => [
                'href' => 'http://lisa.api/user/list?sort=-id&filter%5Bname%5D=%D1%81%D1%83%D0%BF&page=1&per-page=50',
            ],
            'last' => [
                'href' => 'http://lisa.api/user/list?sort=-id&filter%5Bname%5D=%D1%81%D1%83%D0%BF&page=1&per-page=50',
            ],
        ],
        '_meta' => [
            'totalCount' => 19,
            'pageCount' => 1,
            'currentPage' => 1,
            'perPage' => 50,
        ],
    ],
    'filters' => [
        'name' => 'суп',
    ],
    'initialValues' => [
        'activeTeams' => UsersTester::ACTIVE_TEAMS,
        'positions' => UsersTester::POSITIONS,
        'teams' => UsersTester::ALL_TEAMS,
        'userNames' => UsersTester::USER_NAMES,
    ]
];