<?php

use lisa\UsersTester;

return [
    'data' => [
        'models' => [
            0 => [
                'id' => 20,
                'name' => 'Сео Сеошевич 2',
                'login' => 'bpm_seo_2',
                'email' => 'bpm_seo_2@rozetka.com.ua',
                'team' => 20,
                'teamName' => 'Фотостудия',
                'parent_id' => 4,
                'position' => 'seo',
                'positions' => '["seo"]',
                'positionName' => 'Сотрудник seo-отдела (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:37',
                'created_by' => 1,
                'change_date' => '2020-06-25 11:13:13',
                'drfo' => '0',
                'parent' => '4.Константин Куцан',
            ],
            1 => [
                'id' => 22,
                'name' => 'Менеджер Фоткович 2',
                'login' => 'bpm_photoManager_2',
                'email' => 'bpm_photoManager_2@rozetka.com.ua',
                'team' => NULL,
                'teamName' => NULL,
                'parent_id' => 4,
                'position' => 'photoManager',
                'positions' => '["photoManager"]',
                'positionName' => 'Сотрудник фотостудии (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:37',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:41:42',
                'drfo' => '0',
                'parent' => '4.Константин Куцан',
            ],
            2 => [
                'id' => 21,
                'name' => 'Менеджер Фоткович 1',
                'login' => 'bpm_photoManager_1',
                'email' => 'bpm_photoManager_1@rozetka.com.ua',
                'team' => NULL,
                'teamName' => NULL,
                'parent_id' => 4,
                'position' => 'photoManager',
                'positions' => '["photoManager"]',
                'positionName' => 'Сотрудник фотостудии (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:37',
                'created_by' => 1,
                'change_date' => '2020-06-25 11:13:37',
                'drfo' => '0',
                'parent' => '4.Константин Куцан',
            ],
            3 => [
                'id' => 15,
                'name' => 'Тим Лидович 1',
                'login' => 'bpm_teamLead_1',
                'email' => 'bpm_teamLead_1@rozetka.com.ua',
                'team' => 19,
                'teamName' => 'SEO-отдел',
                'parent_id' => 4,
                'position' => 'teamLead',
                'positions' => '["teamLead"]',
                'positionName' => 'Руководитель направления (тимлид) (Все)',
                'status' => 'Заблокированный',
                'create_ts' => '2020-04-13 13:15:35',
                'created_by' => 1,
                'change_date' => '2020-06-28 13:19:51',
                'drfo' => '\'000000015',
                'parent' => '4.Константин Куцан',
            ],
            4 => [
                'id' => 16,
                'name' => 'Тим Лидович 2',
                'login' => 'bpm_teamLead_2',
                'email' => 'bpm_teamLead_2@rozetka.com.ua',
                'team' => 19,
                'teamName' => 'SEO-отдел',
                'parent_id' => 4,
                'position' => 'teamLead',
                'positions' => '["teamLead"]',
                'positionName' => 'Руководитель направления (тимлид) (Все)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:36',
                'created_by' => 1,
                'change_date' => '2020-06-25 10:49:20',
                'drfo' => '\'000000016',
                'parent' => '4.Константин Куцан',
            ],
            5 => [
                'id' => 17,
                'name' => 'Менеджер Продактович 1',
                'login' => 'bpm_productManager_1',
                'email' => 'bpm_productManager_1@rozetka.com.ua',
                'team' => 19,
                'teamName' => 'SEO-отдел',
                'parent_id' => 4,
                'position' => 'productManager',
                'positions' => '["productManager"]',
                'positionName' => 'Продакт-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:36',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:41:00',
                'drfo' => '\'000000017',
                'parent' => '4.Константин Куцан',
            ],
            6 => [
                'id' => 19,
                'name' => 'Сео Сеошевич 1',
                'login' => 'bpm_seo_1',
                'email' => 'bpm_seo_1@rozetka.com.ua',
                'team' => 20,
                'teamName' => 'Фотостудия',
                'parent_id' => 4,
                'position' => 'seo',
                'positions' => '["seo"]',
                'positionName' => 'Сотрудник seo-отдела (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:37',
                'created_by' => 1,
                'change_date' => '2020-06-25 13:18:41',
                'drfo' => '\'000000018',
                'parent' => '4.Константин Куцан',
            ],
            7 => [
                'id' => 18,
                'name' => 'Менеджер Продактович 2',
                'login' => 'bpm_productManager_2',
                'email' => 'bpm_productManager_2@rozetka.com.ua',
                'team' => 19,
                'teamName' => 'SEO-отдел',
                'parent_id' => 4,
                'position' => 'productManager',
                'positions' => '["productManager"]',
                'positionName' => 'Продакт-менеджер (Контент)',
                'status' => 'Активный',
                'create_ts' => '2020-04-13 13:15:36',
                'created_by' => 1,
                'change_date' => '2020-06-24 08:41:05',
                'drfo' => '\'000000018',
                'parent' => '4.Константин Куцан',
            ],
        ],
        '_links' => [
            'self' => [
                'href' => 'http://lisa.api/user/list?filter%5Bcreate_ts%5D=2020-04-13+00%3A00%3A00to2020-04-19+23%3A59%3A59&filter%5Bparent_id%5D=4&sort=drfo&page=1&per-page=50',
            ],
            'first' => [
                'href' => 'http://lisa.api/user/list?filter%5Bcreate_ts%5D=2020-04-13+00%3A00%3A00to2020-04-19+23%3A59%3A59&filter%5Bparent_id%5D=4&sort=drfo&page=1&per-page=50',
            ],
            'last' => [
                'href' => 'http://lisa.api/user/list?filter%5Bcreate_ts%5D=2020-04-13+00%3A00%3A00to2020-04-19+23%3A59%3A59&filter%5Bparent_id%5D=4&sort=drfo&page=1&per-page=50',
            ],
        ],
        '_meta' => [
            'totalCount' => 8,
            'pageCount' => 1,
            'currentPage' => 1,
            'perPage' => 50,
        ],
    ],
    'filters' => [
        'create_ts' => '2020-04-13 00:00:00to2020-04-19 23:59:59',
        'parent_id' => '4',
    ],
    'initialValues' => [
        'activeTeams' => UsersTester::ACTIVETEAMS,
        'positions' => UsersTester::POSITIONS,
        'teams' => UsersTester::TEAMS,
        'userNames' => UsersTester::USER_NAMES,
    ]
];