<?php

use lisa\Constants;

return [
    'case1' => [
        'setting' => [
            'description' => 'Получить модель роли проекта Все',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'name' => 'admin',
            'responseBody' => [
                'model' => [
                    'name' => 'admin',
                    'type' => 1,
                    'description' => 'Администратор',
                    'group' => NULL,
                    'rule_name' => NULL,
                    'data' => NULL,
                    'created_at' => '2020-03-10 12:07:48',
                    'updated_at' => NULL,
                    'project_id' => 0,
                    'permissions' => [
                        'createUser',
                        'updateUser',
                        'blockUser',
                        'viewUser',
                        'requestAddNewItems',
                        'requestUpdateItems',
                        'requestTransferItems',
                        'requestGroupItems',
                        'requestUploadPhoto',
                        'requestCheckHidden',
                        'requestAddFatPortalCat',
                        'requestUpdateFatPortalCat',
                        'requestAddAttrOrValues',
                        'requestUpdateAttrOrValues',
                        'requestStructureDesign',
                        'requestAddUpdateVideo',
                        'requestAddUpdateSizeGrid',
                        'requestAddUpdateTags',
                        'transferRequireChangeToWaitCheck',
                        'transferWaitCheckToRequireChange',
                        'transferWaitCheckToDeclined',
                        'transferWaitCheckToWaitWork',
                        'transferInCheckToWaitWork',
                        'requestCreate',
                        'requestUpdate',
                        'requestCreateRelated',
                        'transferWaitWorkToDeclined',
                        'requestViewOwnRequests',
                        'requestViewDirectionRequests',
                        'requestViewAllRequests',
                        'reportView',
                        'massEdit',
                        'requestViewTeamRequests',
                        'requestDeleteAttachments',
                        'reportLoadAllUsers',
                        'reportLoadMarketUsers',
                        'reportLoadYourTeam',
                        'sellerUpdate',
                        'categoryUpdate',
                        'teamUpdate',
                        'coefUpdate',
                        'fieldsUpdate',
                        'reasonsUpdate',
                        'excludedFieldsUpdate',
                        'viewSplitterModerationRequests',
                        'takeToWork',
                        'priorityUpdate',
                        'transferInWorkToWaitWork',
                        'transferPartialCompleteToInWork',
                        'transferCompletedToInWork',
                        'transferPartialCompleteToClosed',
                        'transferOnHoldToPartialComplete',
                        'transferOnHoldToCompleted',
                        'viewDashboardsByCommand',
                        'viewDashboardsByDirection',
                        'viewOwnDashboards',
                        'viewAllDashboards',
                        'transferCompletedToClosed',
                        'transferInCheckToDeclined',
                        'transferInCheckToRequireChange',
                        'transferInWorkToCompleted',
                        'transferInWorkToDeclined',
                        'transferInWorkToOnHold',
                        'transferInWorkToPartialComplete',
                        'transferOnHoldToInWork',
                        'transferWaitCheckToInCheck',
                        'transferWaitWorkToInWork',
                        'seeTeamTemplates',
                        'seeDirectionTemplates',
                        'seeAllTemplates',
                        'updateTemplates',
                        'errorsUpdate',
                        'transferRequireChangeToDeclined',
                        'seeHiddenCrossCheckFields',
                        '50kReports',
                        'SvDistributionUpdate',
                    ],
                    'projects' => Constants::PROJECTS,
                ],
                'initialPermissions' => Constants::PROJECT_PERMISSIONS,
            ],
        ]
    ],

    'case2' => [
        'setting' => [
            'description' => 'Получить модель роли проекта Контент',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'name' => 'supervisor',
            'responseBody' => [
                'model' => [
                    'name' => 'supervisor',
                    'type' => 1,
                    'description' => 'Супервайзер',
                    'group' => NULL,
                    'rule_name' => NULL,
                    'data' => NULL,
                    'created_at' => '2020-03-10 12:07:48',
                    'updated_at' => NULL,
                    'project_id' => 1,
                    'permissions' => [
                        'massEdit',
                        'reportLoadYourTeam',
                        'reportView',
                        'requestAddAttrOrValues',
                        'requestAddFatPortalCat',
                        'requestAddNewItems',
                        'requestAddUpdateSizeGrid',
                        'requestAddUpdateTags',
                        'requestAddUpdateVideo',
                        'requestCheckHidden',
                        'requestCreate',
                        'requestCreateRelated',
                        'requestGroupItems',
                        'requestStructureDesign',
                        'requestTransferItems',
                        'requestUpdateAttrOrValues',
                        'requestUpdateFatPortalCat',
                        'requestUpdateItems',
                        'requestUploadPhoto',
                        'requestViewDirectionRequests',
                        'seeTeamTemplates',
                        'takeToWork',
                        'transferCompletedToClosed',
                        'transferCompletedToInWork',
                        'transferInCheckToDeclined',
                        'transferInCheckToRequireChange',
                        'transferInCheckToWaitWork',
                        'transferInWorkToCompleted',
                        'transferInWorkToDeclined',
                        'transferInWorkToOnHold',
                        'transferInWorkToPartialComplete',
                        'transferInWorkToWaitWork',
                        'transferOnHoldToInWork',
                        'transferPartialCompleteToClosed',
                        'transferPartialCompleteToInWork',
                        'transferRequireChangeToInCheck',
                        'transferRequireChangeToWaitCheck',
                        'transferRequireChangeToDeclined',
                        'transferWaitCheckToDeclined',
                        'transferWaitCheckToInCheck',
                        'transferWaitCheckToRequireChange',
                        'transferWaitCheckToWaitWork',
                        'transferWaitWorkToDeclined',
                        'transferWaitWorkToInWork',
                        'viewDashboardsByCommand',
                        'viewSplitterModerationRequests',
                        'viewUser',
                        'seeHiddenCrossCheckFields',
                    ],
                    'projects' => Constants::PROJECTS,
                ],
                'initialPermissions' => Constants::PROJECT_PERMISSIONS,
            ],
        ]
    ],

    'case3' => [
        'setting' => [
            'description' => 'Получить пустую модель команды для создания',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'responseBody' => [
                'model' => [
                    'name' => NULL,
                    'type' => 1,
                    'description' => NULL,
                    'group' => NULL,
                    'rule_name' => NULL,
                    'data' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'project_id' => 1,
                    'permissions' => [
                    ],
                    'projects' => Constants::PROJECTS,
                ],
                'initialPermissions' => Constants::PROJECT_PERMISSIONS,
            ],
        ]
    ]
];
