<?php

use lisa\UsersTester;

return [
    'case1' => [
        'setting' => [
            'description' => 'Получить модель роли проекта Все',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'name' => 'admin',
            'responseBody' => [
                'model' => [
                    'name' => 'admin',
                    'type' => 1,
                    'description' => 'Администратор',
                    'group' => NULL,
                    'rule_name' => NULL,
                    'data' => NULL,
                    'created_at' => '2020-03-10 12:07:48',
                    'updated_at' => NULL,
                    'project_id' => 0,
                    'permissions' => [
                        0 => 'createUser',
                        1 => 'updateUser',
                        2 => 'blockUser',
                        3 => 'viewUser',
                        4 => 'requestAddNewItems',
                        5 => 'requestUpdateItems',
                        6 => 'requestTransferItems',
                        7 => 'requestGroupItems',
                        8 => 'requestUploadPhoto',
                        9 => 'requestCheckHidden',
                        10 => 'requestAddFatPortalCat',
                        11 => 'requestUpdateFatPortalCat',
                        12 => 'requestAddAttrOrValues',
                        13 => 'requestUpdateAttrOrValues',
                        14 => 'requestStructureDesign',
                        15 => 'requestAddUpdateSC',
                        16 => 'requestAddUpdateVideo',
                        17 => 'requestAddUpdateSizeGrid',
                        18 => 'requestAddUpdateTags',
                        19 => 'transferRequireChangeToWaitCheck',
                        20 => 'transferWaitCheckToRequireChange',
                        21 => 'transferWaitCheckToDeclined',
                        22 => 'transferWaitCheckToWaitWork',
                        23 => 'transferInCheckToWaitWork',
                        24 => 'requestCreate',
                        25 => 'requestUpdate',
                        26 => 'requestCreateRelated',
                        27 => 'transferWaitWorkToDeclined',
                        28 => 'requestViewOwnRequests',
                        29 => 'requestViewDirectionRequests',
                        30 => 'requestViewAllRequests',
                        31 => 'reportView',
                        32 => 'massEdit',
                        33 => 'requestViewTeamRequests',
                        34 => 'requestDeleteAttachments',
                        35 => 'reportLoadAllUsers',
                        36 => 'reportLoadMarketUsers',
                        37 => 'reportLoadYourTeam',
                        38 => 'sellerUpdate',
                        39 => 'categoryUpdate',
                        40 => 'teamUpdate',
                        41 => 'coefUpdate',
                        42 => 'fieldsUpdate',
                        43 => 'reasonsUpdate',
                        44 => 'excludedFieldsUpdate',
                        45 => 'viewSplitterModerationRequests',
                        46 => 'takeToWork',
                        47 => 'priorityUpdate',
                        48 => 'transferInWorkToWaitWork',
                        49 => 'transferPartialCompleteToInWork',
                        50 => 'transferCompletedToInWork',
                        51 => 'transferPartialCompleteToClosed',
                        52 => 'transferOnHoldToPartialComplete',
                        53 => 'transferOnHoldToCompleted',
                        54 => 'viewDashboardsByCommand',
                        55 => 'viewDashboardsByDirection',
                        56 => 'viewOwnDashboards',
                        57 => 'viewAllDashboards',
                        58 => 'transferCompletedToClosed',
                        59 => 'transferInCheckToDeclined',
                        60 => 'transferInCheckToRequireChange',
                        61 => 'transferInWorkToCompleted',
                        62 => 'transferInWorkToDeclined',
                        63 => 'transferInWorkToOnHold',
                        64 => 'transferInWorkToPartialComplete',
                        65 => 'transferOnHoldToInWork',
                        66 => 'transferWaitCheckToInCheck',
                        67 => 'transferWaitWorkToInWork',
                        68 => 'seeTeamTemplates',
                        69 => 'seeDirectionTemplates',
                        70 => 'seeAllTemplates',
                        71 => 'updateTemplates',
                        72 => 'errorsUpdate',
                        73 => 'transferRequireChangeToDeclined',
                    ],
                    'projects' => UsersTester::PROJECTS,
                ],
                'initialPermissions' => UsersTester::PROJECT_PERMISSIONS,
            ],
        ]
    ],

    'case2' => [
        'setting' => [
            'description' => 'Получить модель роли проекта Контент',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'name' => 'supervisor',
            'responseBody' => [
                'model' => [
                    'name' => 'supervisor',
                    'type' => 1,
                    'description' => 'Супервайзер',
                    'group' => NULL,
                    'rule_name' => NULL,
                    'data' => NULL,
                    'created_at' => '2020-03-10 12:07:48',
                    'updated_at' => NULL,
                    'project_id' => 1,
                    'permissions' => [
                        0 => 'massEdit',
                        1 => 'reportLoadYourTeam',
                        2 => 'reportView',
                        3 => 'requestAddAttrOrValues',
                        4 => 'requestAddFatPortalCat',
                        5 => 'requestAddNewItems',
                        6 => 'requestAddUpdateSC',
                        7 => 'requestAddUpdateSizeGrid',
                        8 => 'requestAddUpdateTags',
                        9 => 'requestAddUpdateVideo',
                        10 => 'requestCheckHidden',
                        11 => 'requestCreate',
                        12 => 'requestCreateRelated',
                        13 => 'requestGroupItems',
                        14 => 'requestStructureDesign',
                        15 => 'requestTransferItems',
                        16 => 'requestUpdateAttrOrValues',
                        17 => 'requestUpdateFatPortalCat',
                        18 => 'requestUpdateItems',
                        19 => 'requestUploadPhoto',
                        20 => 'requestViewDirectionRequests',
                        21 => 'seeTeamTemplates',
                        22 => 'takeToWork',
                        23 => 'transferCompletedToClosed',
                        24 => 'transferCompletedToInWork',
                        25 => 'transferInCheckToDeclined',
                        26 => 'transferInCheckToRequireChange',
                        27 => 'transferInCheckToWaitWork',
                        28 => 'transferInWorkToCompleted',
                        29 => 'transferInWorkToDeclined',
                        30 => 'transferInWorkToOnHold',
                        31 => 'transferInWorkToPartialComplete',
                        32 => 'transferInWorkToWaitWork',
                        33 => 'transferOnHoldToInWork',
                        34 => 'transferPartialCompleteToClosed',
                        35 => 'transferPartialCompleteToInWork',
                        36 => 'transferRequireChangeToInCheck',
                        37 => 'transferRequireChangeToWaitCheck',
                        38 => 'transferRequireChangeToDeclined',
                        39 => 'transferWaitCheckToDeclined',
                        40 => 'transferWaitCheckToInCheck',
                        41 => 'transferWaitCheckToRequireChange',
                        42 => 'transferWaitCheckToWaitWork',
                        43 => 'transferWaitWorkToDeclined',
                        44 => 'transferWaitWorkToInWork',
                        45 => 'viewDashboardsByCommand',
                        46 => 'viewSplitterModerationRequests',
                        47 => 'viewUser',
                    ],
                    'projects' => UsersTester::PROJECTS,
                ],
                'initialPermissions' => UsersTester::PROJECT_PERMISSIONS,
            ],
        ]
    ],

    'case3' => [
        'setting' => [
            'description' => 'Получить пустую модель команды для создания',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case1.php',
        'provider_data' => [
            'responseBody' => [
                'model' => [
                    'name' => NULL,
                    'type' => 1,
                    'description' => NULL,
                    'group' => NULL,
                    'rule_name' => NULL,
                    'data' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'project_id' => 1,
                    'permissions' => [
                    ],
                    'projects' => UsersTester::PROJECTS,
                ],
                'initialPermissions' => UsersTester::PROJECT_PERMISSIONS,
            ],
        ]
    ]
];
