<?php

return [
    'case4' => [
        'setting' => [
            'description' => 'Перевод из "В работе" в "Отменена"',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case.php',
        'provider_data' => [
            'requestParameter' => 'change-reason',
            'requestBody' => [
                'Request[reason]' => 'Отменить',
                'Request[reason_id]' => '11',
                'Request[status]' => '4',
                "_csrf-backend" => null,
                'keys',
                'keys',
            ],
            'fields' => [
                'RequestField[111]' => '0',
                'RequestField[121]' => '',
                'RequestField[15]' => '1',
                'RequestField[1]' => '1',
                'RequestField[20]' => '',
                'RequestField[21]' => '',
                'RequestField[22]' => '',
                'RequestField[23]' => '',
                'RequestField[24]' => '',
                'RequestField[25]' => '',
                'RequestField[26]' => '',
                'RequestField[27]' => '',
                'RequestField[31]' => '',
                'RequestField[65]' => '0',
                'RequestField[66]' => '0',
                'RequestField[68]' => '0',
                'RequestField[69]' => '0',
                'RequestField[70]' => '0',
                'RequestField[71]' => '0',
                'RequestField[76]' => '0',
                'RequestField[77]' => '0',
                'RequestField[88]' => '0',
                'RequestField[8]' => '1',
                'RequestField[93]' => '0',
                'RequestField[94]' => '0',
                'RequestField[9]' => '1',
                'Request[addedAttachments]' => '[]',
                'Request[amount_to_work]' => '10',
                'Request[attachment_folder]' => '9c4f8356ab2ddca8b9dcafb8b511df50',
                'Request[author_id]' => '2',
                'Request[category_id]' => '1',
                'Request[correction_comment]' => '',
                'Request[deletedAttachments]' => '[]',
                'Request[description]' => 'description',
                'Request[manager_id]' => '11',
                'Request[planned_start_date]' => '',
                'Request[priority]' => '2',
                'Request[recommendations]' => '',
                'Request[report_period_id]' => '',
                'Request[result_comment]' => '',
                'Request[seller_id]' => '83',
                'Request[subject]' => 'Добавление новых товаров (Работа с товарами Розетки)',
                'Request[supervisor_comment]' => '',
                'Request[supervisor_id]' => '4',
            ],
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 1,
                    "supervisor_id" => 4,
                    "manager_id" => 11,
                    "status" => 4,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    "created_at" => '2020-01-01 00:00:00',
                    "correction_comment" => '',
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 83,
                    "recommendations" => '',
                    "reason_id" => 11,
                    "reason" => 'Отменить',
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => '2020-01-01 00:00:03',
                    "actual_finish_date" => null,
                    "supervisor_process_date" => '2020-01-01 00:00:02',
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => '',
                    "supervisor_comment" => '',
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => '{"1": 1}',
                ],
                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case5' => [
        'setting' => [
            'description' => 'Перевод из "В работе" в "Ожидает взятия в работу"',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case.php',
        'provider_data' => [
            'requestParameter' => 'appoint-manager',
            'requestBody' => [
                'Request[manager_id]' => '12',
                "_csrf-backend" => null,
                'keys',
            ],
            'fields' => [
                'RequestField[111]' => '0',
                'RequestField[121]' => '',
                'RequestField[15]' => '1',
                'RequestField[1]' => '1',
                'RequestField[20]' => '',
                'RequestField[21]' => '',
                'RequestField[22]' => '',
                'RequestField[23]' => '',
                'RequestField[24]' => '',
                'RequestField[25]' => '',
                'RequestField[26]' => '',
                'RequestField[27]' => '',
                'RequestField[31]' => '',
                'RequestField[65]' => '0',
                'RequestField[66]' => '0',
                'RequestField[68]' => '0',
                'RequestField[69]' => '0',
                'RequestField[70]' => '0',
                'RequestField[71]' => '0',
                'RequestField[76]' => '0',
                'RequestField[77]' => '0',
                'RequestField[88]' => '0',
                'RequestField[8]' => '1',
                'RequestField[93]' => '0',
                'RequestField[94]' => '0',
                'RequestField[9]' => '1',
                'Request[addedAttachments]' => '[]',
                'Request[amount_to_work]' => '10',
                'Request[attachment_folder]' => '9c4f8356ab2ddca8b9dcafb8b511df50',
                'Request[author_id]' => '2',
                'Request[category_id]' => '1',
                'Request[correction_comment]' => '',
                'Request[deletedAttachments]' => '[]',
                'Request[description]' => 'description',
                'Request[manager_id]' => '12',
                'Request[planned_start_date]' => '',
                'Request[priority]' => '2',
                'Request[recommendations]' => '',
                'Request[report_period_id]' => '',
                'Request[result_comment]' => '',
                'Request[seller_id]' => '83',
                'Request[subject]' => 'Добавление новых товаров (Работа с товарами Розетки)',
                'Request[supervisor_comment]' => '',
                'Request[supervisor_id]' => '4',
            ],
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 1,
                    "supervisor_id" => 4,
                    "manager_id" => 12,
                    "status" => 5,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    "created_at" => '2020-01-01 00:00:00',
                    "correction_comment" => '',
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 83,
                    "recommendations" => '',
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => '2020-01-01 00:00:03',
                    "actual_finish_date" => null,
                    "supervisor_process_date" => '2020-01-01 00:00:02',
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => '',
                    "supervisor_comment" => '',
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => '{"1": 1}',
                ],
                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case7' => [
        'setting' => [
            'description' => 'Перевод из "В работе" в "Ожидает (ризоны)"',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case.php',
        'provider_data' => [
            'requestParameter' => 'change-reason',
            'requestBody' => [
                'Request[reason]' => 'Ожидать',
                'Request[reason_id]' => '1',
                'Request[status]' => '7',
                "_csrf-backend" => null,
                'keys',
                'keys',
            ],
            'fields' => [
                'RequestField[111]' => '0',
                'RequestField[121]' => '',
                'RequestField[15]' => '1',
                'RequestField[1]' => '1',
                'RequestField[20]' => '',
                'RequestField[21]' => '',
                'RequestField[22]' => '',
                'RequestField[23]' => '',
                'RequestField[24]' => '',
                'RequestField[25]' => '',
                'RequestField[26]' => '',
                'RequestField[27]' => '',
                'RequestField[31]' => '',
                'RequestField[65]' => '0',
                'RequestField[66]' => '0',
                'RequestField[68]' => '0',
                'RequestField[69]' => '0',
                'RequestField[70]' => '0',
                'RequestField[71]' => '0',
                'RequestField[76]' => '0',
                'RequestField[77]' => '0',
                'RequestField[88]' => '0',
                'RequestField[8]' => '1',
                'RequestField[93]' => '0',
                'RequestField[94]' => '0',
                'RequestField[9]' => '1',
                'Request[addedAttachments]' => '[]',
                'Request[amount_to_work]' => '10',
                'Request[attachment_folder]' => '9c4f8356ab2ddca8b9dcafb8b511df50',
                'Request[author_id]' => '2',
                'Request[category_id]' => '1',
                'Request[correction_comment]' => '',
                'Request[deletedAttachments]' => '[]',
                'Request[description]' => 'description',
                'Request[manager_id]' => '11',
                'Request[planned_start_date]' => '',
                'Request[priority]' => '2',
                'Request[recommendations]' => '',
                'Request[report_period_id]' => '',
                'Request[result_comment]' => '',
                'Request[seller_id]' => '83',
                'Request[subject]' => 'Добавление новых товаров (Работа с товарами Розетки)',
                'Request[supervisor_comment]' => '',
                'Request[supervisor_id]' => '4',
            ],
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 1,
                    "supervisor_id" => 4,
                    "manager_id" => 11,
                    "status" => 7,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    "created_at" => '2020-01-01 00:00:00',
                    "correction_comment" => '',
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 83,
                    "recommendations" => '',
                    "reason_id" => 1,
                    "reason" => 'Ожидать',
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => '2020-01-01 00:00:03',
                    "actual_finish_date" => null,
                    "supervisor_process_date" => '2020-01-01 00:00:02',
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => '',
                    "supervisor_comment" => '',
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => '{"1": 1}',
                ],
                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case8' => [
        'setting' => [
            'description' => 'Перевод из "В работе" в "Частично выполнен"',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case.php',
        'provider_data' => [
            'requestParameter' => 'complete',
            'requestBody' => [
                'RequestField[111]' => '10',
                'RequestField[21]' => '1',
                'RequestField[22]' => '6',
                'RequestField[23]' => '11',
                'RequestField[24]' => '15',
                'RequestField[25]' => '18',
                'RequestField[26]' => '22',
                'RequestField[27]' => '24',
                'RequestField[31]' => '48',
                'RequestField[66]' => '10',
                'RequestField[68]' => '10',
                'RequestField[69]' => '10',
                'RequestField[70]' => '10',
                'RequestField[71]' => '10',
                'RequestField[76]' => '10',
                'RequestField[77]' => '10',
                'RequestField[88]' => '10',
                'RequestField[93]' => '10',
                'RequestField[94]' => '10',
                'Request[awaiting_correction]' => '0',
                'Request[reason_id]' => '15',
                'Request[status]' => '8',
                'Request[result_comment]' => 'Комментарий к результату задачи',
                "_csrf-backend" => null,
            ],
            'fields' => [
                'RequestField[111]' => '10',
                'RequestField[121]' => '',
                'RequestField[15]' => '1',
                'RequestField[1]' => '1',
                'RequestField[20]' => '',
                'RequestField[21]' => '1',
                'RequestField[22]' => '6',
                'RequestField[23]' => '11',
                'RequestField[24]' => '15',
                'RequestField[25]' => '18',
                'RequestField[26]' => '22',
                'RequestField[27]' => '24',
                'RequestField[31]' => '48',
                'RequestField[65]' => '0',
                'RequestField[66]' => '10',
                'RequestField[68]' => '10',
                'RequestField[69]' => '10',
                'RequestField[70]' => '10',
                'RequestField[71]' => '10',
                'RequestField[76]' => '10',
                'RequestField[77]' => '10',
                'RequestField[88]' => '10',
                'RequestField[8]' => '1',
                'RequestField[93]' => '10',
                'RequestField[94]' => '10',
                'RequestField[9]' => '1',
                'Request[addedAttachments]' => '[]',
                'Request[amount_to_work]' => '10',
                'Request[attachment_folder]' => '982cabb0b062bd7eb1f4f289ceec2db1',
                'Request[author_id]' => '2',
                'Request[category_id]' => '1',
                'Request[correction_comment]' => '',
                'Request[deletedAttachments]' => '[]',
                'Request[description]' => 'description',
                'Request[manager_id]' => '11',
                'Request[planned_start_date]' => '',
                'Request[priority]' => '2',
                'Request[recommendations]' => '',
                'Request[report_period_id]' => '',
                'Request[result_comment]' => 'Комментарий к результату задачи',
                'Request[seller_id]' => '83',
                'Request[subject]' => 'Добавление новых товаров (Работа с товарами Розетки)',
                'Request[supervisor_comment]' => '',
                'Request[supervisor_id]' => '4',
            ],
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 1,
                    "supervisor_id" => 4,
                    "manager_id" => 11,
                    "status" => 8,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    "created_at" => '2020-01-01 00:00:00',
                    "correction_comment" => '',
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 83,
                    "recommendations" => '',
                    "reason_id" => 15,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => '2020-01-01 00:00:03',
                    //"actual_finish_date" => null,
                    "supervisor_process_date" => '2020-01-01 00:00:02',
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => 'Комментарий к результату задачи',
                    "supervisor_comment" => '',
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => '{"1": 1}',
                ],
                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 21,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 22,
                        'value' => 6,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 23,
                        'value' => 11,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 24,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 25,
                        'value' => 18,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 26,
                        'value' => 22,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 27,
                        'value' => 24,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 31,
                        'value' => 48,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 150.1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 150.1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 66,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 68,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 69,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 70,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 71,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 76,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 77,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 88,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 93,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 94,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 111,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],

    'case9' => [
        'setting' => [
            'description' => 'Перевод из "В работе" в "Выполнен"',
        ],
        'fixture_data' => include __DIR__ . '/fixture/case.php',
        'provider_data' => [
            'requestParameter' => 'complete',
            'requestBody' => [
                'RequestField[111]' => '10',
                'RequestField[21]' => '1',
                'RequestField[22]' => '6',
                'RequestField[23]' => '11',
                'RequestField[24]' => '15',
                'RequestField[25]' => '18',
                'RequestField[26]' => '22',
                'RequestField[27]' => '24',
                'RequestField[31]' => '48',
                'RequestField[66]' => '10',
                'RequestField[68]' => '10',
                'RequestField[69]' => '10',
                'RequestField[70]' => '10',
                'RequestField[71]' => '10',
                'RequestField[76]' => '10',
                'RequestField[77]' => '10',
                'RequestField[88]' => '10',
                'RequestField[93]' => '10',
                'RequestField[94]' => '10',
                'Request[awaiting_correction]' => '0',
                'Request[result_comment]' => 'Комментарий к результату задачи',
                'Request[status]' => '9',
                "_csrf-backend" => null,
            ],
            'fields' => [
                'RequestField[111]' => '10',
                'RequestField[121]' => '',
                'RequestField[15]' => '1',
                'RequestField[1]' => '1',
                'RequestField[20]' => '',
                'RequestField[21]' => '1',
                'RequestField[22]' => '6',
                'RequestField[23]' => '11',
                'RequestField[24]' => '15',
                'RequestField[25]' => '18',
                'RequestField[26]' => '22',
                'RequestField[27]' => '24',
                'RequestField[31]' => '48',
                'RequestField[65]' => '0',
                'RequestField[66]' => '10',
                'RequestField[68]' => '10',
                'RequestField[69]' => '10',
                'RequestField[70]' => '10',
                'RequestField[71]' => '10',
                'RequestField[76]' => '10',
                'RequestField[77]' => '10',
                'RequestField[88]' => '10',
                'RequestField[8]' => '1',
                'RequestField[93]' => '10',
                'RequestField[94]' => '10',
                'RequestField[9]' => '1',
                'Request[addedAttachments]' => '[]',
                'Request[amount_to_work]' => '10',
                'Request[attachment_folder]' => '982cabb0b062bd7eb1f4f289ceec2db1',
                'Request[author_id]' => '2',
                'Request[category_id]' => '1',
                'Request[correction_comment]' => '',
                'Request[deletedAttachments]' => '[]',
                'Request[description]' => 'description',
                'Request[manager_id]' => '11',
                'Request[planned_start_date]' => '',
                'Request[priority]' => '2',
                'Request[recommendations]' => '',
                'Request[report_period_id]' => '',
                'Request[result_comment]' => 'Комментарий к результату задачи',
                'Request[seller_id]' => '83',
                'Request[subject]' => 'Добавление новых товаров (Работа с товарами Розетки)',
                'Request[supervisor_comment]' => '',
                'Request[supervisor_id]' => '4',
            ],
            'db' => [
                'requests' => [
                    "id" => 1,
                    "author_id" => 2,
                    "type_id" => 1,
                    "supervisor_id" => 4,
                    "manager_id" => 11,
                    "status" => 9,
                    "direction" => 1,
                    "priority" => 2,
                    "awaiting_correction" => 0,
                    "created_at" => '2020-01-01 00:00:00',
                    "correction_comment" => '',
                    "amount_to_work" => 10,
                    "subject" => "Добавление новых товаров (Работа с товарами Розетки)",
                    "description" => 'description',
                    "attachments" => '[]',
                    "category_id" => 1,
                    "seller_id" => 83,
                    "recommendations" => '',
                    "reason_id" => null,
                    "reason" => null,
                    "parent_id" => null,
                    "planned_start_date" => null,
                    "planned_finish_date" => null,
                    "actual_start_date" => '2020-01-01 00:00:03',
                    //"actual_finish_date" => null,
                    "supervisor_process_date" => '2020-01-01 00:00:02',
                    "supervisor_check_date" => null,
                    "difficulty" => null,
                    "result_comment" => 'Комментарий к результату задачи',
                    "supervisor_comment" => '',
                    //"last_change_status_date" => "2020-01-01 00:00:01",
                    "team_direction" => 3,
                    "report_period_id" => null,
                    "sync_source_id" => null,
                    "sv_report_periods" => '{"1": 1}',
                ],
                'requests_fields' => [
                    [
                        'request_id' => 1,
                        'field_id' => 1,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 8,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 9,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 15,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 21,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 22,
                        'value' => 6,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 23,
                        'value' => 11,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 24,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 25,
                        'value' => 18,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 26,
                        'value' => 22,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 27,
                        'value' => 24,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 31,
                        'value' => 48,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 49,
                        'value' => 150.1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 50,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 51,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 52,
                        'value' => 15,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 53,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 54,
                        'value' => 1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 60,
                        'value' => 0,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 64,
                        'value' => 150.1,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 66,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 68,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 69,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 70,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 71,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 76,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 77,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 88,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 93,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 94,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 101,
                        'value' => null,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 111,
                        'value' => 10,
                    ],
                    [
                        'request_id' => 1,
                        'field_id' => 122,
                        'value' => null,
                    ],
                ]
            ]
        ]
    ],
];
