<?php

return [
    'tabsData' => \lisa\UsersTester::tableMassButtons(999),
    'currentTab' => 'all',
    'columns' => [
        'item.id' => [
            'value' => 'id',
            'text' => 'Номер задачи',
        ],
        'item.subject' => [
            'value' => 'subject',
            'text' => 'Заголовок',
        ],
        'item.type_id' => [
            'value' => 'type_id',
            'text' => 'Тип',
            'filter' => [
                'type' => 'select',
                'multiple' => true,
                'items' => [
                    0 => [
                        'id' => 1,
                        'text' => 'Добавление новых товаров',
                    ],
                    1 => [
                        'id' => 2,
                        'text' => 'Добавление/изменение информации в существующих товарах',
                    ],
                    2 => [
                        'id' => 3,
                        'text' => 'Перенос товаров',
                    ],
                    3 => [
                        'id' => 4,
                        'text' => 'Группировка товаров',
                    ],
                    4 => [
                        'id' => 5,
                        'text' => 'Заливка фото с фотостудии',
                    ],
                    5 => [
                        'id' => 6,
                        'text' => 'Проверка скрытых товаров',
                    ],
                    6 => [
                        'id' => 7,
                        'text' => 'Добавление нового портала/раздела фат-меню/категории товаров',
                    ],
                    7 => [
                        'id' => 8,
                        'text' => 'Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров',
                    ],
                    8 => [
                        'id' => 9,
                        'text' => 'Добавление параметров/значений',
                    ],
                    9 => [
                        'id' => 10,
                        'text' => 'Изменение существующих параметров/значений',
                    ],
                    10 => [
                        'id' => 11,
                        'text' => 'Проектирование структуры',
                    ],
                    11 => [
                        'id' => 12,
                        'text' => 'Добавление новых СЦ/изменение существующих СЦ',
                    ],
                    12 => [
                        'id' => 13,
                        'text' => 'Добавление/изменение видео',
                    ],
                    13 => [
                        'id' => 14,
                        'text' => 'Добавление/изменение размерной сетки',
                    ],
                    14 => [
                        'id' => 15,
                        'text' => 'Добавление/изменение тегов',
                    ],
                ],
            ],
        ],
        'item.author_id' => [
            'value' => 'author_id',
            'text' => 'Автор',
            'filter' => [
                'type' => 'autocomplete',
                'url' => '/user/list?fields=id,name&parent&filter[name]=',
                'itemText' => 'name',
                'itemValue' => 'id',
            ],
        ],
        'item.supervisor_id' => [
            'value' => 'supervisor_id',
            'text' => 'Супервайзер',
            'filter' => [
                'type' => 'autocomplete',
                'url' => '/user/list?fields=id,name&parent&filter[name]=',
                'itemText' => 'name',
                'itemValue' => 'id',
            ],
        ],
        'item.manager_id' => [
            'value' => 'manager_id',
            'text' => 'Контент-менеджер',
            'filter' => [
                'type' => 'autocomplete',
                'url' => '/user/list?fields=id,name&parent&filter[name]=',
                'itemText' => 'name',
                'itemValue' => 'id',
            ],
        ],
        'item.status' => [
            'value' => 'status',
            'text' => 'Статус',
            'filter' => [
                'type' => 'select',
                'multiple' => true,
                'items' => [
                    0 => [
                        'id' => 1,
                        'text' => 'Новая',
                    ],
                    1 => [
                        'id' => 2,
                        'text' => 'Готова для распределения',
                    ],
                    2 => [
                        'id' => 3,
                        'text' => 'На доработке',
                    ],
                    3 => [
                        'id' => 4,
                        'text' => 'Отменена',
                    ],
                    4 => [
                        'id' => 5,
                        'text' => 'Ожидает взятия в работу',
                    ],
                    5 => [
                        'id' => 6,
                        'text' => 'В работе',
                    ],
                    6 => [
                        'id' => 7,
                        'text' => 'Ожидает',
                    ],
                    7 => [
                        'id' => 8,
                        'text' => 'Частично выполнена',
                    ],
                    8 => [
                        'id' => 9,
                        'text' => 'Выполнена',
                    ],
                    9 => [
                        'id' => 11,
                        'text' => 'Закрыта',
                    ],
                    10 => [
                        'id' => -1,
                        'text' => '(не задано)',
                    ],
                ],
            ],
        ],
        'item.previous_status' => [
            'value' => 'previous_status',
            'text' => 'Предыдущий статус',
            'filter' => [
                'type' => 'select',
                'multiple' => true,
                'items' => [
                    0 => [
                        'id' => 1,
                        'text' => 'Новая',
                    ],
                    1 => [
                        'id' => 2,
                        'text' => 'Готова для распределения',
                    ],
                    2 => [
                        'id' => 3,
                        'text' => 'На доработке',
                    ],
                    3 => [
                        'id' => 4,
                        'text' => 'Отменена',
                    ],
                    4 => [
                        'id' => 5,
                        'text' => 'Ожидает взятия в работу',
                    ],
                    5 => [
                        'id' => 6,
                        'text' => 'В работе',
                    ],
                    6 => [
                        'id' => 7,
                        'text' => 'Ожидает',
                    ],
                    7 => [
                        'id' => 8,
                        'text' => 'Частично выполнена',
                    ],
                    8 => [
                        'id' => 9,
                        'text' => 'Выполнена',
                    ],
                    9 => [
                        'id' => 11,
                        'text' => 'Закрыта',
                    ],
                    10 => [
                        'id' => -1,
                        'text' => '(не задано)',
                    ],
                ],
            ],
        ],
        'item.cross_check_manager_id' => [
            'value' => 'cross_check_manager_id',
            'text' => 'Кросс-чек менеджер',
            'filter' => [
                'type' => 'autocomplete',
                'url' => '/user/list?fields=id,name&parent&filter[name]=',
                'itemText' => 'name',
                'itemValue' => 'id',
            ],
        ],
        'item.cross_check_status' => [
            'value' => 'cross_check_status',
            'text' => 'Кросс-чек статус',
            'filter' => [
                'type' => 'select',
                'multiple' => true,
                'items' => [
                    0 => [
                        'id' => 0,
                        'text' => 'Не прошла кросс-чек',
                    ],
                    1 => [
                        'id' => 1,
                        'text' => 'На кросс-чеке',
                    ],
                    2 => [
                        'id' => 2,
                        'text' => 'Кросс-чек пройден',
                    ],
                    3 => [
                        'id' => -1,
                        'text' => '(не задано)',
                    ],
                ],
            ],
        ],
        'item.direction' => [
            'value' => 'direction',
            'text' => 'Направление задачи',
            'filter' => [
                'type' => 'select',
                'multiple' => true,
                'items' => [
                    0 => [
                        'id' => 0,
                        'text' => 'Определяется типом задачи',
                    ],
                    1 => [
                        'id' => 1,
                        'text' => 'Работа с товарами Розетки',
                    ],
                    2 => [
                        'id' => 2,
                        'text' => 'Работа с товарами Маркетплейса',
                    ],
                ],
            ],
        ],
        'item.team_direction' => [
            'value' => 'team_direction',
            'text' => 'Направление команды',
            'filter' => [
                'type' => 'select',
                'multiple' => true,
                'items' => [
                    0 => [
                        'id' => 1,
                        'text' => 'Управление отделом',
                    ],
                    1 => [
                        'id' => 2,
                        'text' => 'Работа с товарами Маркетплейса',
                    ],
                    2 => [
                        'id' => 3,
                        'text' => 'Работа с товарами Rozetka',
                    ],
                    3 => [
                        'id' => 4,
                        'text' => 'Работа с группами',
                    ],
                    4 => [
                        'id' => 5,
                        'text' => 'Работа с проектированием структур + фильтрами',
                    ],
                    5 => [
                        'id' => 6,
                        'text' => 'Работа с порталами, фат-меню, категориями',
                    ],
                ],
            ],
        ],
        'item.category_id' => [
            'value' => 'category_id',
            'text' => 'Категория товаров',
            'filter' => [
                'type' => 'autocomplete',
                'url' => '/category/list?fields=id,title&parent&filter[title]=',
                'itemText' => 'title',
                'itemValue' => 'id',
            ],
        ],
        'item.seller_id' => [
            'filter' => [
                'itemText' => 'title',
                'itemValue' => 'owox_id',
                'type' => 'autocomplete',
                'url' => '/market-supervisor/list?fields=owox_id,title&parent&filter[title]=',
            ],
            'value' => 'seller_id',
            'text' => 'Продавец',
        ],
    ],
    'filters' => [
    ],
    'permissions' => [
        'requestCreate' => true,
    ],
    'data' => [
        'models' => [
            0 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Выполнена',
                'awaiting_correction' => 0,
                'id' => 25,
                'subject' => 'Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров (Определяется типом задачи)',
                'type_id' => 'Добавление/изменение информации в существующих порталах/фат-меню/категориях товаров',
                'author_id' => 'Тим Лидович 1',
                'supervisor_id' => 'Супервайзер Категоркин 18',
                'manager_id' => 'Менеджер Контентович 2А',
                'status' => 'Закрыта',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => 'Видео к товару',
                'seller_id' => 'Маркетплейс (общий)',
                'requestAttachments' => [
                ],
                'statusKey' => 11,
            ],
            1 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Выполнена',
                'awaiting_correction' => 0,
                'id' => 24,
                'subject' => 'Добавление нового портала/раздела фат-меню/категории товаров (Определяется типом задачи)',
                'type_id' => 'Добавление нового портала/раздела фат-меню/категории товаров',
                'author_id' => 'Тим Лидович 2',
                'supervisor_id' => 'Супервайзер Категоркин 15',
                'manager_id' => 'Менеджер Контентович 2Б',
                'status' => 'Закрыта',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => 'Авиабилеты',
                'seller_id' => NULL,
                'requestAttachments' => [
                ],
                'statusKey' => 11,
            ],
            2 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Частично выполнена',
                'awaiting_correction' => 0,
                'id' => 23,
                'subject' => 'Добавление/изменение тегов (Определяется типом задачи)',
                'type_id' => 'Добавление/изменение тегов',
                'author_id' => 'Менеджер Продактович 1',
                'supervisor_id' => 'Супервайзер Категоркин 15',
                'manager_id' => 'Менеджер Контентович 2А',
                'status' => 'Закрыта',
                'cross_check_manager_id' => 'Менеджер Контентович 2Б',
                'cross_check_status' => 'Кросс-чек пройден',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => NULL,
                'seller_id' => 'Маркетплейс (общий)',
                'requestAttachments' => [
                ],
                'statusKey' => 11,
            ],
            3 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'В работе',
                'awaiting_correction' => 0,
                'id' => 22,
                'subject' => 'Добавление/изменение видео (Определяется типом задачи)',
                'type_id' => 'Добавление/изменение видео',
                'author_id' => 'Менеджер Продактович 2',
                'supervisor_id' => 'Супервайзер Категоркин 15',
                'manager_id' => 'Менеджер Контентович 2А',
                'status' => 'Выполнена',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => 'Видео к товару',
                'seller_id' => 'anytech',
                'requestAttachments' => [
                ],
                'statusKey' => 9,
            ],
            4 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'В работе',
                'awaiting_correction' => 0,
                'id' => 21,
                'subject' => 'Добавление/изменение тегов (Определяется типом задачи)',
                'type_id' => 'Добавление/изменение тегов',
                'author_id' => 'Менеджер Продактович 2',
                'supervisor_id' => 'Супервайзер Категоркин 15',
                'manager_id' => 'Менеджер Контентович 1А',
                'status' => 'Выполнена',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 9,
            ],
            5 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'В работе',
                'awaiting_correction' => 0,
                'id' => 20,
                'subject' => 'Добавление/изменение видео (Определяется типом задачи)',
                'type_id' => 'Добавление/изменение видео',
                'author_id' => 'Тим Лидович 1',
                'supervisor_id' => 'Супервайзер Категоркин 18',
                'manager_id' => 'Менеджер Контентович 1Б',
                'status' => 'Частично выполнена',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 8,
            ],
            6 => [
                'parent_id' => 3,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'В работе',
                'awaiting_correction' => 0,
                'id' => 19,
                'subject' => 'Добавление/изменение размерной сетки (Определяется типом задачи)',
                'type_id' => 'Добавление/изменение размерной сетки',
                'author_id' => 'Тим Лидович 2',
                'supervisor_id' => 'Супервайзер Категоркин 18',
                'manager_id' => 'Менеджер Контентович 2Б',
                'status' => 'Ожидает',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => 'Авиабилеты',
                'seller_id' => NULL,
                'requestAttachments' => [
                ],
                'statusKey' => 7,
            ],
            7 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'В работе',
                'awaiting_correction' => 0,
                'id' => 18,
                'subject' => 'Изменение существующих параметров/значений (Определяется типом задачи)',
                'type_id' => 'Изменение существующих параметров/значений',
                'author_id' => 'Сео Сеошевич 2',
                'supervisor_id' => 'Супервайзер Проектенко 17',
                'manager_id' => 'Менеджер Контентович 1А',
                'status' => 'Ожидает',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с проектированием структур + фильтрами',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 7,
            ],
            8 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Ожидает взятия в работу',
                'awaiting_correction' => 0,
                'id' => 17,
                'subject' => 'Проектирование структуры (Определяется типом задачи)',
                'type_id' => 'Проектирование структуры',
                'author_id' => 'Тим Лидович 2',
                'supervisor_id' => 'Супервайзер Проектенко 17',
                'manager_id' => 'Менеджер Контентович 2Б',
                'status' => 'В работе',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с проектированием структур + фильтрами',
                'category_id' => 'Авиабилеты',
                'seller_id' => NULL,
                'requestAttachments' => [
                ],
                'statusKey' => 6,
            ],
            9 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Частично выполнена',
                'awaiting_correction' => 1,
                'id' => 16,
                'subject' => 'Добавление параметров/значений (Определяется типом задачи)',
                'type_id' => 'Добавление параметров/значений',
                'author_id' => 'Сео Сеошевич 2',
                'supervisor_id' => 'Супервайзер Проектенко 14',
                'manager_id' => 'Менеджер Контентович 2Б',
                'status' => 'В работе (ожидает исправлений)',
                'cross_check_manager_id' => 'Менеджер Контентович 2А',
                'cross_check_status' => 'На кросс-чеке',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с проектированием структур + фильтрами',
                'category_id' => 'Видео к товару',
                'seller_id' => 'Маркетплейс (общий)',
                'requestAttachments' => [
                ],
                'statusKey' => 6,
            ],
            10 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Выполнена',
                'awaiting_correction' => 1,
                'id' => 15,
                'subject' => 'Добавление параметров/значений (Определяется типом задачи)',
                'type_id' => 'Добавление параметров/значений',
                'author_id' => 'Сео Сеошевич 1',
                'supervisor_id' => 'Супервайзер Проектенко 14',
                'manager_id' => 'Менеджер Контентович 1Б',
                'status' => 'В работе (ожидает исправлений)',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с проектированием структур + фильтрами',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 6,
            ],
            11 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Готова для распределения',
                'awaiting_correction' => 0,
                'id' => 14,
                'subject' => 'Добавление новых СЦ/изменение существующих СЦ (Работа с товарами Розетки)',
                'type_id' => 'Добавление новых СЦ/изменение существующих СЦ',
                'author_id' => 'Менеджер Продактович 1',
                'supervisor_id' => 'Супервайзер Начальникович 1',
                'manager_id' => 'Менеджер Контентович 2А',
                'status' => 'Ожидает взятия в работу',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Розетки',
                'team_direction' => 'Работа с товарами Rozetka',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 5,
            ],
            12 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Новая',
                'awaiting_correction' => 0,
                'id' => 13,
                'subject' => 'Добавление новых товаров (Работа с товарами Розетки)',
                'type_id' => 'Добавление новых товаров',
                'author_id' => 'Тим Лидович 1',
                'supervisor_id' => 'Супервайзер Начальникович 1',
                'manager_id' => 'Менеджер Контентович 1Б',
                'status' => 'Ожидает взятия в работу',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Розетки',
                'team_direction' => 'Работа с товарами Rozetka',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 5,
            ],
            13 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Новая',
                'awaiting_correction' => 0,
                'id' => 12,
                'subject' => 'Добавление нового портала/раздела фат-меню/категории товаров (Определяется типом задачи)',
                'type_id' => 'Добавление нового портала/раздела фат-меню/категории товаров',
                'author_id' => 'Тим Лидович 1',
                'supervisor_id' => 'Супервайзер Категоркин 15',
                'manager_id' => 'Менеджер Контентович 1А',
                'status' => 'Ожидает взятия в работу',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с порталами, фат-меню, категориями',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 5,
            ],
            14 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'В работе',
                'awaiting_correction' => 0,
                'id' => 11,
                'subject' => 'Проектирование структуры (Определяется типом задачи)',
                'type_id' => 'Проектирование структуры',
                'author_id' => 'Менеджер Продактович 1',
                'supervisor_id' => 'Супервайзер Проектенко 14',
                'manager_id' => 'Менеджер Контентович 1Б',
                'status' => 'Отменена',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с проектированием структур + фильтрами',
                'category_id' => 'Видео к товару',
                'seller_id' => NULL,
                'requestAttachments' => [
                ],
                'statusKey' => 4,
            ],
            15 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Ожидает взятия в работу',
                'awaiting_correction' => 0,
                'id' => 10,
                'subject' => 'Изменение существующих параметров/значений (Определяется типом задачи)',
                'type_id' => 'Изменение существующих параметров/значений',
                'author_id' => 'Сео Сеошевич 1',
                'supervisor_id' => 'Супервайзер Проектенко 14',
                'manager_id' => 'Менеджер Контентович 2А',
                'status' => 'Отменена',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с проектированием структур + фильтрами',
                'category_id' => NULL,
                'seller_id' => 'Маркетплейс (общий)',
                'requestAttachments' => [
                ],
                'statusKey' => 4,
            ],
            16 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Готова для распределения',
                'awaiting_correction' => 0,
                'id' => 9,
                'subject' => 'Группировка товаров (Определяется типом задачи)',
                'type_id' => 'Группировка товаров',
                'author_id' => 'Менеджер Продактович 1',
                'supervisor_id' => 'Супервайзер Групповушкин 13',
                'manager_id' => NULL,
                'status' => 'На доработке',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с группами',
                'category_id' => 'Авиабилеты',
                'seller_id' => NULL,
                'requestAttachments' => [
                ],
                'statusKey' => 3,
            ],
            17 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Готова для распределения',
                'awaiting_correction' => 0,
                'id' => 8,
                'subject' => 'Добавление/изменение информации в существующих товарах (Работа с товарами Маркетплейса)',
                'type_id' => 'Добавление/изменение информации в существующих товарах',
                'author_id' => 'Тим Лидович 1',
                'supervisor_id' => 'Супервайзер Начальникович 2',
                'manager_id' => NULL,
                'status' => 'На доработке',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Маркетплейса',
                'team_direction' => 'Работа с товарами Маркетплейса',
                'category_id' => NULL,
                'seller_id' => 'anytech',
                'requestAttachments' => [
                ],
                'statusKey' => 3,
            ],
            18 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Новая',
                'awaiting_correction' => 0,
                'id' => 7,
                'subject' => 'Заливка фото с фотостудии (Работа с товарами Розетки)',
                'type_id' => 'Заливка фото с фотостудии',
                'author_id' => 'Менеджер Фоткович 1',
                'supervisor_id' => 'Супервайзер Начальникович 1',
                'manager_id' => NULL,
                'status' => 'На доработке',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Розетки',
                'team_direction' => 'Работа с товарами Rozetka',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Rozetka',
                'requestAttachments' => [
                ],
                'statusKey' => 3,
            ],
            19 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Новая',
                'awaiting_correction' => 0,
                'id' => 6,
                'subject' => 'Перенос товаров (Работа с товарами Маркетплейса)',
                'type_id' => 'Перенос товаров',
                'author_id' => 'Менеджер Продактович 1',
                'supervisor_id' => 'Супервайзер Руководько 1',
                'manager_id' => NULL,
                'status' => 'Готова для распределения',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Маркетплейса',
                'team_direction' => 'Работа с товарами Маркетплейса',
                'category_id' => NULL,
                'seller_id' => 'Маркетплейс (общий)',
                'requestAttachments' => [
                ],
                'statusKey' => 2,
            ],
            20 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Новая',
                'awaiting_correction' => 0,
                'id' => 5,
                'subject' => 'Перенос товаров (Работа с товарами Розетки)',
                'type_id' => 'Перенос товаров',
                'author_id' => 'Менеджер Продактович 2',
                'supervisor_id' => 'Супервайзер Начальникович 1',
                'manager_id' => NULL,
                'status' => 'Готова для распределения',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Розетки',
                'team_direction' => 'Работа с товарами Rozetka',
                'category_id' => 'Авиабилеты',
                'seller_id' => 'Rozetka',
                'requestAttachments' => [
                ],
                'statusKey' => 2,
            ],
            21 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'Новая',
                'awaiting_correction' => 0,
                'id' => 4,
                'subject' => 'Перенос товаров (Работа с товарами Маркетплейса)',
                'type_id' => 'Перенос товаров',
                'author_id' => 'Менеджер Продактович 1',
                'supervisor_id' => 'Супервайзер Начальникович 1',
                'manager_id' => NULL,
                'status' => 'Готова для распределения',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Маркетплейса',
                'team_direction' => 'Работа с товарами Маркетплейса',
                'category_id' => NULL,
                'seller_id' => 'Euromart',
                'requestAttachments' => [
                ],
                'statusKey' => 2,
            ],
            22 => [
                'parent_id' => NULL,
                'child_count' => 1,
                'photo_load_status' => 0,
                'previous_status' => NULL,
                'awaiting_correction' => 0,
                'id' => 3,
                'subject' => 'Группировка товаров (Определяется типом задачи)',
                'type_id' => 'Группировка товаров',
                'author_id' => 'Менеджер Продактович 2',
                'supervisor_id' => 'Супервайзер Групповушкин 13',
                'manager_id' => NULL,
                'status' => 'Новая',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Определяется типом задачи',
                'team_direction' => 'Работа с группами',
                'category_id' => NULL,
                'seller_id' => 'Маркетплейс (общий)',
                'requestAttachments' => [
                ],
                'statusKey' => 1,
            ],
            23 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => NULL,
                'awaiting_correction' => 0,
                'id' => 2,
                'subject' => 'Добавление новых товаров (Работа с товарами Маркетплейса)',
                'type_id' => 'Добавление новых товаров',
                'author_id' => 'Тим Лидович 2',
                'supervisor_id' => 'Супервайзер Руководько 1',
                'manager_id' => NULL,
                'status' => 'Новая',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Маркетплейса',
                'team_direction' => 'Работа с товарами Маркетплейса',
                'category_id' => NULL,
                'seller_id' => 'Маркетплейс (общий)',
                'requestAttachments' => [
                ],
                'statusKey' => 1,
            ],
            24 => [
                'parent_id' => NULL,
                'child_count' => 0,
                'photo_load_status' => 0,
                'previous_status' => 'На доработке',
                'awaiting_correction' => 0,
                'id' => 1,
                'subject' => 'Добавление/изменение информации в существующих товарах (Работа с товарами Розетки)',
                'type_id' => 'Добавление/изменение информации в существующих товарах',
                'author_id' => 'Тим Лидович 2',
                'supervisor_id' => 'Супервайзер Начальникович 2',
                'manager_id' => NULL,
                'status' => 'Новая  (Вернулась с доработки)',
                'cross_check_manager_id' => NULL,
                'cross_check_status' => 'Не прошла кросс-чек',
                'direction' => 'Работа с товарами Розетки',
                'team_direction' => 'Работа с товарами Rozetka',
                'category_id' => 'Видео к товару',
                'seller_id' => 'anytech',
                'requestAttachments' => [
                ],
                'statusKey' => 1,
            ],
        ],
        '_links' => [
            'self' => [
                'href' => 'http://lisa.api/request/list/all?per-page=50&page=1',
            ],
            'first' => [
                'href' => 'http://lisa.api/request/list/all?per-page=50&page=1',
            ],
            'last' => [
                'href' => 'http://lisa.api/request/list/all?per-page=50&page=1',
            ],
        ],
        '_meta' => [
            'totalCount' => 25,
            'pageCount' => 1,
            'currentPage' => 1,
            'perPage' => 50,
        ],
    ],
];